### ISSUE TITLE
[Request] Llama-3 prompt templates.

### ISSUE THREAD

**Issue by Spacellary** [agnaistic/agnai#1006]
**Is your feature request related to a problem? Please describe.**
There isn't an included prompting template that suits Llama-3/3.1 models.

**Describe the solution you'd like**
The inclusion of an included prompting template that suits Llama-3/3.1 models.

**Describe alternatives you've considered**
Using ChatML and Alpaca temporarily.

**Additional context**

![image](https://github.com/user-attachments/assets/121cc9c0-c558-4157-bfb4-80595fea6e1a)

**Llama-3 documentation:**
https://llama.meta.com/docs/model-cards-and-prompt-formats/meta-llama-3/

**Comment by sceuick** [comment]
Done.

**Comment by Spacellary** [comment]
Awesome!

**Comment by Spacellary** [comment]
@sceuick Gave it a go on the web, unless it's not available yet but trying now I am seeing the EOS token bleeding into responses as shown in the screenshots, happens in all generations. Using both Llama3 preset prompt format and sampler.

I noted the model in question for reference.

[![dVkFs4I.md.png](https://iili.io/dVkFs4I.md.png)](https://freeimage.host/i/dVkFs4I)
[![dVkFQ2t.md.png](https://iili.io/dVkFQ2t.md.png)](https://freeimage.host/i/dVkFQ2t)

**Comment by Spacellary** [comment]
Considering L3 models, this seems to only happen to Lumimaid-8/70B, while the base Llama3 Instruct Mancer model doesn't have this issue.

**Comment by sceuick** [comment]
I'd add `<|` or `<|eot_id|>` as a stopping string.

**Comment by Spacellary** [comment]
[![dVksV14.md.png](https://iili.io/dVksV14.md.png)](https://freeimage.host/i/dVksV14)

I had tried that without success surprisingly enough.

**Comment by Spacellary** [comment]
I will try other models inferencing locally later when I get some time. Might just be a matter of Lumimaid 0.1 vs 0.2. Will look to consult Mancer on it. Thanks and have a good day!

**Comment by sceuick** [comment]
Typically I leave the stopping string handling up to the service. They're just passed through.
There are some inferencers that include the stopping result with the response. I can look into handling this on Agnai's side as well.

**Comment by Spacellary** [comment]
@sceuick I see. That would be great too.

**Comment by Spacellary** [comment]
@sceuick – Some further feedback:

The underlying issue seemed to be with Lumimaid **0.1** models served by Mancer. They've since added their newer versions, **Lumimaid 0.2** which do not have this issue and work well as expected. So I'd say that's all good.

Thanks again for incorporating the Llama-3 format so swiftly.
