### ISSUE TITLE
On Android, it's hard to copy/paste values between fields

### ISSUE THREAD

**Issue by acidbubbles** [agnaistic/agnai#103]
This one might be tricky but I think it's worth at least noting for now.

On Android, when trying to Select All + Copy text from either the chat input field (chat screen) or from the character attribute fields (character edit screen), it's very hard to get the popup on long tap. I think it's because there's something that happens "on click" on those fields that prevents Android from showing the popup. It's hard to reproduce on PC, making this one harder to fix. You can see however when you click on a field that it "flashes" with a white border for a second and then reverts back. It might be related. I'll try and explore this using localtunnel, but you might already have an idea. It wasn't obvious just by looking at the code since there's only a onkeyup and a onchange on the input, as far as I can tell.

**Comment by sceuick** [comment]
I have an android device I can investigate with. Thanks for raising the issue.

**Comment by acidbubbles** [comment]
I wanted to look at the problem but something since then has changed I think, because I can copy text, there's no more "flickering" when touching the field. So, closing :)
