### ISSUE TITLE
Include the built-in presets in the Presets screen

### ISSUE THREAD

**Issue by acidbubbles** [agnaistic/agnai#104]
Related to my comment https://github.com/luminai-companion/agn-ai/issues/75#issuecomment-1485809841.

- Right now, there's a presets list in the Settings screen, but it's hard to know which does what.
- It's also difficult to customize a preset, since you need to open the code to see the values

I think there's a fairly simple solution.

- In the Presets screen, include the default presets, not only the custom ones.
- This means the "duplicate" button can be used to customize an existing preset by making a copy, and;
- It'll be possible to "explore" the different presets.
- Also, add another "description field to explain what it does. For example, "Use third person, prioritize creativity, allows some repetition, NSFW bias" or something like that.
- Add a link in the Settings / Presets screen to go to the Presets list

It _sounds_ like a simple approach. What do you think?

**Comment by sceuick** [comment]
Thank you for clarifying that it _sounds_ simple :joy: 
Yeah, I agree. It does sound fairly simple. It would certainly be worth it if there was a broader set to choose from. I put a _very_ small amount of effort in choosing the current default presets just to get me off the ground.

**Comment by acidbubbles** [comment]
If it sounds good I'll try and make a PR when I have time, at least with the general shape of the feature. And yeah, good presets sound like something very subjective and hard to test reliably. Just having a few as "good examples" is fine to get people started already!

**Comment by acidbubbles** [comment]
Quick question, right now the default and user presets are completely different things, meaning everywhere you work with them you have to check if it's a default one, and if not fallback to loading the actual preset. I was wondering if I did the same in the presets screen or if you preferred refactoring this to have a common presets store.

For now I'll move forward with a smaller PR but it might be worth thinking about.

![image](https://user-images.githubusercontent.com/34192666/228309736-cfa98164-1fc9-4dec-aa5d-b1d876abf1d1.png)

**Comment by acidbubbles** [comment]
The PR: https://github.com/luminai-companion/agn-ai/pull/106
