### ISSUE TITLE
Add alpaca.cpp as an AI (OR: Generic AI API Integration)

### ISSUE THREAD

**Issue by acidbubbles** [agnaistic/agnai#112]
This is the "best" option right now for a chatbot that runs locally, without an expensive video card. It's very slow, but I'm sure people would like having something like this running locally. I wouldn't rush this implementation but it's definitely interesting to have. Especially with Docker, running Alpaca-Turbo in Docker would mean you'd get the full agn-ai experience fully locally, with no dependencies on Internet, as long as you have enough RAM. Well, given you can download the quantized weights from a reliable source...

A project that runs it as a chatbot: https://github.com/ViperX7/Alpaca-Turbo
Alpaca.cpp itself: https://github.com/ViperX7/alpaca.cpp_

Here's what it looks like in the console:

![image](https://user-images.githubusercontent.com/34192666/228639665-eafc686b-c154-4165-a15c-f63c0efebe64.png)

The main question is whether to use Alpaca-Turbo as the API backend (it uses websockets right now), run alpaca.cpp_ directly, wait for a new project to offer an API layer for alpaca.cpp (there are discussions about making an open standardized LLM API: https://alexatallah.notion.site/RFC-LLM-API-Standard-c8f15d24bd2f4ab98b656f08cdc1c4fb)

Update: An API is already available with Alpaca-Turbo: https://github.com/ViperX7/Alpaca-Turbo/pull/16

To further the idea of the standardized API, I think this would mean having a "Standardized LLM URL" rather than "Alpaca integration", so that issue is maybe more generic than just an alpaca integration, opening the door to an alternative implementation: providing a raw URL, header and template for the API source, allowing users to configure their own backends instead of having to create a new issue for every one. (Or at least integrations would just be an HTTP POST template with variables).

**Comment by sceuick** [comment]
Does alpaca.cpp use the same API as llama.cpp? IIRC the `llama.cpp` repo added a KoboldAI compatible API.

**Comment by acidbubbles** [comment]
I'm not aware of the llama.cpp implementation, so I can't say. There is however this new project that seems promising: https://github.com/rustformers/llama-rs - It looks like an executable.

There are tons of forks including https://github.com/LostRuins/llamacpp-for-kobold which could be interesting (though I'm not sure I understand the added value of going through kobold)

To be honest the forks of this projects are a complete mess, it's all over the place :D But nonetheless while very slow and not exactly stable, it works (the ViperX7 one at least) and runs on low end devices without any Internet dependencies.

The slowness IS an issue though, especially if you are running on low end devices. Chatting with a bot that takes 2 minutes to answer every time is not a great experience, but this might change as the alpaca libs get better I guess.

**Comment by rondlite** [comment]
> though I'm not sure I understand the added value of going through kobold

As far as I understand it is a Kobold compatible API meaning it would not run kobold in the traditional sense but just has an API that works the same, so no need for extra changes on agn-ai for that.

**Comment by acidbubbles** [comment]
So, it doesn't look like ViperX's one is actually kobold-compatible, but I feel like there are many options out there.

Which brings an interesting question... if I can have multiple Kobold backends... should I have the ability to create as many backends as I want? Including multiple Kobold backends with each their own URL?

**Comment by acidbubbles** [comment]
I'll close this for now, I think someone could open a better issue with a specific implementation suggestion. For now, I'm watching Alpaca and the new StabilityAI LLM from afar, see if something "stable" gets out of it that warrants being integrated.
