### ISSUE TITLE
Refactor: Normalized presets implementation

### ISSUE THREAD

**Issue by acidbubbles** [agnaistic/agnai#113]
Before going into too much details about this, I thought I'd start by creating a simple ticket so you can either say "Don't mess with this" or "I don't care, do whatever you want" :)

So, long story short, the "problem" is that there's a typescript presets file, and user presets. It means in multiple places, the code is checking if it's one or the other, we cannot easily clone them in the same way, they even have different typings.

I suggest:

1. A normalized means of referencing presets, such as `default:name` and `user:name`
2. The presets store would contain both default and user presets
3. The presets would have a new readonly field which would help the UI determine whether some options like delete and edit would be enabled
4. I would use this opportunity to add a documentation field

It's probably not a super complicated refactor but it spans many files.

What do you think? Does that make sense, and is this something you're already working on?

I'd also like to bring the idea that presets should be extensible in the future, so extensions can be included (luminai middlewares) and/or make backend-specific fields like OpenAI API Key become a dictionary instead of a typed field (so other, custom backends wouldn't have a different structure to deal with).

NOTE: I'd do this before completing https://github.com/luminai-companion/agn-ai/issues/104

**Comment by sceuick** [comment]
Well hopefully at the recent BigRefactor I can close this now.
They've been vastly "reigned in".
