### ISSUE TITLE
bug: Changing Turbo temperature may cause responses to be cut short 

### ISSUE THREAD

**Issue by malfoyslastname** [agnaistic/agnai#121]
An anonymous user reported that when they change the default Turbo temperature, the responses they get are cut short.
I have never seen anyone else report this before so I am worried a mysterious additional factor is at play here.

I will attempt to reproduce and PR. I will notify this thread when I start working on this bug.

**Comment by sceuick** [comment]
The `max_tokens` is passed through correctly in the payload as far as I can tell. I'm not sure what else would affect it. The generation settings in OpenAI payloads are very limited.

**Comment by sceuick** [comment]
Closing this as unconfirmed.
