### ISSUE TITLE
feat: Make more prompt engineering information available (token count etc)

### ISSUE THREAD

**Issue by malfoyslastname** [agnaistic/agnai#122]
An anonymous user requested prompt engineering information to be available somehow, e.g. in "Chat editing" mode, treating it like "advanced" mode. Example of desired data:

- Token counts (character defs, character defs + conversation history about to be sent, individual messages)
- "Actual full prompt instead of the approximated one"
- "Something more detailed, like what local users get in the logs or tavern users get in the console, but on the website."

UX must be considered before implementing. What data to make available, where and how?

I *might* start working on this later. If I do, I will notify this thread.

**Comment by sceuick** [comment]
- I'd like to add token counts very soon. Just need to work out a nice place in the various UI's to put them. I think creating a `TokenInput` variant of `TextInput` component for these would probably be the way to go and floating the value just below the input/textarea element may do the trick? Open the suggestions.
- The 'prompt' is best effort given the data that is in the front-end. It should be the same prompt as the same code is used in the backend and frontend to build it. The "approximation" is saying that the data used to generate this particular response could have changed. E.g. the preceding message may have been edited after the response was generated.
- The other caveat is that the prompt is completely different for Turbo. It would be an annoying refactor to display what is being sent to Turbo as that code only resides in the OpenAI adapter.
- "Something more detailed, ..." - Is this for being self-hosting? What specifically are they chasing?

**Comment by sceuick** [comment]
Done.
