### ISSUE TITLE
UX: Presets should be service-specific and hide options irrelevant to selected service

### ISSUE THREAD

**Issue by malfoyslastname** [agnaistic/agnai#128]
The assumption here is that presets are always used in combination with a single service. (Is the assumption true?) In order to greatly simplify preset creation UI, presets should be service-specific and exclude settings irrelevant to that service. The user would first select a service and then be able to set its relevant options.

**Comment by ewof** [comment]
there are cases for self hostable models like llama or pygmalion where presets will be used for the ooba, kobold, and horde adapters

**Comment by malfoyslastname** [comment]
Then instead of
`Select service -> See preset parameters for this service`
it should be
`Select service category -> See preset parameters for this service category`

**Comment by malfoyslastname** [comment]
see also #174

**Comment by acidbubbles** [comment]
Oops I missed it @malfoyslastname! I'll reject the other one and add the suggestions here. I was meaning to just do it but I'd like to know if there is an implementation preference first.

Original text:

I wanted to implement #148 as well as refactor the UI so the presets would only show field that are applicable to a given backend. I have two options to do so and I'd like your opinion first.

Presets would have a backend discriminator, making them backend-specific. So, only the relevant fields for a backend would exist on a given preset, and the preset can only be used for a specific backend

## Option 1: Shared presets, filtered in UI

I would add a "PresetFields" list, which would contain the list of keys of the GenPreset object that a given backend support. Each UI field would individually be shown or hidden depending on whether the backend it was assigned to supports it or not.

This is closer the actual implementation, with a single class for all presets. This also makes it possible to share a preset between multiple backends.

## Option 2: A preset class an UI per backend

This is my preferred option. I would create a preset for each backend, and a UI for each backend. That would result in some duplication (E.g. Horde v.s. KoboldUI could share the same base class and UI though) but would make it easier to make a better tailored UI, e.g. for OpenAI that has more "advanced" functions like tokens to avoid.

If you're okay with it, I'd try and do Option 2.

**Comment by acidbubbles** [comment]
I would also suggest something further... I suggested it elsewhere but I think it'd make sense for this refactoring.

I'd split the Settings menu in two menus. Backends (or AIs) and Settings. The former would contain backend settings, the default preset AND the ability to manage presets _for a given backend_. The latter would simply be the UI settings.

This sounds more logical to me anyway, but that's an opinion.

**Comment by malfoyslastname** [comment]
detailed UX proposal (also posted to Discord for discussion)
https://gist.github.com/malfoyslastname/408de73329ad04f2d5052236037cd89f

**Comment by sceuick** [comment]
This has now been done.
