### ISSUE TITLE
Feature request: Make taking anonymous screenshots easier

### ISSUE THREAD

**Issue by malfoyslastname** [agnaistic/agnai#129]
Users should be able to easily anonymize their conversation for screenshotting. Such a hypothetical feature would at least censor the user's display name and avatar, and possibly even censor occurrences of their display name inside chat messages. Ideally, there would be a screenshot feature that does all that and also exports a .png of all loaded messages.

**Comment by sceuick** [comment]
Has been resolved after merging your PR #171
