### ISSUE TITLE
bug: Local runtime exception prevents agnai from loading

### ISSUE THREAD

**Issue by malfoyslastname** [agnaistic/agnai#131]
When running agnai locally, the agnai webpage is only a black screen. Multiple anonymous users reported this, and I experienced it myself on my fork (I had to do my coding on the original repo, which didn't have this bug while my fork did, even when set to the same tag).

When I experienced this issue, it complained about a runtime exception in solidjs.

![1680435117](https://user-images.githubusercontent.com/128472336/229350103-35ed6cd1-74dc-4934-a8e2-8b4a8815224c.png)

It is unknown what causes this. I will keep investigating, but the more eyes on this, the better, I would consider this high priority considering multiple people have reported experiencing it.

What an anonymous user did to set up agnai:
> clone
> npm install
> npm run build:all
> npm run start:win
> http://localhost:3001/

I did pretty much the same but for Linux and with URL http://localhost:1234 (why is 3001 seemingly the API for me but the frontend for that other user? did they accidentally load the wrong url or are the ports different on Windows and Linux?)

**Comment by malfoyslastname** [comment]
Current solution:
- Install pnpm: https://pnpm.io/installation
- run `pnpm install`

A solution for regular users which does not involve pnpm is desired

**Comment by sceuick** [comment]
`solid-js` updated to 1.7.1 which for some reason is breaking the app. I've pinned it to `1.6.9`. So pulling the latest code from dev and running `npm install` again will fix it.
