### ISSUE TITLE
bug: Need to refresh agnai to properly join a multi-user room

### ISSUE THREAD

**Issue by malfoyslastname** [agnaistic/agnai#135]
- Accept a room invite
- Join the chat
- The chatroom says that you've been removed from it, but you can still post and see new posts. However, you cannot see names (they show up as empty string), and avatars are replaced with the default icon
- Refresh agnai to fix

There might be a mystery factor at play because someone else in that room reported not experiencing the bug.

**Comment by sceuick** [comment]
I've had to refactor some of the room logic to allow removal of users, but have their profiles remain in the chat.
This will just be related to that. I'll sort it out at the same time as #136 .

**Comment by malfoyslastname** [comment]
let's close unless this is reported again
