### ISSUE TITLE
Installation misunderstanding

### ISSUE THREAD

**Issue by zordak0x70** [agnaistic/agnai#137]
I feel really stupid, because I just installed agnaistic ai and got to the point where the local server was created with port 3001; but now I don't know what to do, I have no idea how to use these resources, how to complete the installation

**Comment by ewof** [comment]
3001 is the server port
if u ran with `pnpm start` u should be able to put `http://localhost:1234` (or whatever the ip of the machine it's running on is) and use the frontend. if u didn't setup mongodb (which u dont have to) u won't be able to make accounts and will only be able to use guest mode.

**Comment by sceuick** [comment]
It looks like one of the dependencies (solid-js) updated and was breaking new installs.
I've pinned the version to the working version. You can pull down the latest code and run `npm install` again.
From there you should be able to `npm run start` or `npm run start:Win` and it should all work again.
