### ISSUE TITLE
Resilience: Better handling of disconnected MongoDB

### ISSUE THREAD

**Issue by acidbubbles** [agnaistic/agnai#139]
This might not be in the high priority list, but I noticed that in a lot of places, if MongoDB is down or simply not running, the UI will act as if there were no chats, memories, etc. There will be no errors surfacing, despite the server returning 500. Well there's a small toast in the corner.

But more specifically, if MongoDB restarts, the Agnai backend will not attempt to reconnect, forcing a manual restart of the server.

**Comment by sceuick** [comment]
This may already be fixed.
