### ISSUE TITLE
delete character does not delete the character

### ISSUE THREAD

**Issue by rondlite** [agnaistic/agnai#14]
I tried on the demo install and local, but delete character does not delete anything, it just says it does because mongodb does not return an error.
Could it need an actual ObjectId instead of a string?

**Comment by sceuick** [comment]
Is this authed or guest access?

**Comment by sceuick** [comment]
Ah it looks like the parameters are reversed in the function call from the API.
Line 81-ish in `srv/api/character.ts` that calls `store.characters.deleteCharacter` has the parameters reversed.
I'll convert it to an object it.

**Comment by sceuick** [comment]
Should now be fixed with 761a68227cdd66d7910bc189c5b29e6530711dcd
