### ISSUE TITLE
OpenAI: Include the user ID in the OpenAI API payload

### ISSUE THREAD

**Issue by acidbubbles** [agnaistic/agnai#143]
I'm not sure how OpenAI can "reach out" in case of "abuse" but it looks like the user ID will be used to pinpoint the issue in those cases. I think it would be responsible to include either the user ID, or a hashed user ID, or a unique ID associated with the user (so it can be reset) and include it in the API call: https://platform.openai.com/docs/guides/safety-best-practices

I think it would also be good to consider implementing https://platform.openai.com/docs/guides/moderation/overview (to flag specific categories like "sexual/minors" for example), while leaving it an option to turn it on or off, and which categories to detect.

That would allow making the bot safer to use and more in line with OpenAI policies.

**Comment by acidbubbles** [comment]
Further more (and it was discussed for psychological help too on the Discord I think) there should be something that tells the user that everything is made up, etc. etc.

> Automated systems (including conversational AI and chatbots) must disclose to users that they are interacting with an AI system. With the exception of chatbots that depict historical public figures, products that simulate another person must either have that person's explicit consent or be clearly labeled as “simulated” or “parody.”

This would obviously be something we want to be able to turn off, but by default it should be there.

**Comment by acidbubbles** [comment]
(If we're adding things to the OpenAI adapter, I'd love to be able to also configure the logit_bias, rather than having a super-specific "antiBond" option. logic_bias presets would be nice.)

**Comment by malfoyslastname** [comment]
> I'm not sure how OpenAI can "reach out" in case of "abuse" but it looks like the user ID will be used to pinpoint the issue in those cases.

The user ID field is in the case of a centralized key. Agnai is a bring-your-own-key service. If OpenAI has a problem with someone's usage they will email (or ban) them directly.

**Comment by acidbubbles** [comment]
It's BYOK but that doesn't mean the key isn't shared. Anyway it's a very minor thing (I think).

**Comment by sceuick** [comment]
Going to close this for now unless there is some demand for it.
