### ISSUE TITLE
Repetitive messages (bug)

### ISSUE THREAD

**Issue by Alfiandrr** [agnaistic/agnai#147]
So when I Import json file from the bot prompts, at first the chat goes well, but suddenly the bot say something repetitive constantly even I change my chats

**Comment by sceuick** [comment]
Can you provide a bit more info? I'm after:

- which AI service you're using
- guest or logged in
- rough chat size
- max tokens and max context limit.

**Comment by sceuick** [comment]
Closed due to no response
