### ISSUE TITLE
Ability to customize a preset in the chat settings

### ISSUE THREAD

**Issue by acidbubbles** [agnaistic/agnai#148]
Here's the use case. I have a chat, with e.g. 80 max new tokens in the preset. Now, I want to tweak that for a specific chat. However, either I see the generic values (which are not at all from the preset), OR I can toggle the "use preset" option, which makes it read-only.

I think there could simply be a "Customize this preset" button and that would be fine.

I also think that by default, the chat settings should be read only by default, right now it's pretty confusing to me to see "Service preset and fallback" but underneath, see unrelated values and system prompt.

If this didn't make sense, let me know and I'll add screenshots of what I mean.

On a side note, I think I understand that this creates "overrides" on the service preset in the chat document, right? I'm wondering if it wouldn't be simpler to use the same chat gen settings everywhere, and either refer to a preset or not.

**Comment by khanonnie** [comment]
Been meaning to open a PR which at least prevents the Use Preset toggle from resetting to the defaults (so that if you want to customize an existing preset on a per-chat basis, you can select the preset, and then toggle off Use Preset to make a tweak to a single setting for just that chat).

It's been working for me to basically satisfy this use case, for example if I want to tweak the prompt or temperature for a particular part of a story I'm writing, but it's maybe not as straightforward to users as a "Customize This Preset" button..

**Comment by acidbubbles** [comment]
A simple implementation would be to simply have an "Apply preset" button, which would copy the preset in the chat's settings, rather than a toggle. So, by default it's whatever preset you have in the drop down (read only) and the "Apply" button changes that drop down to "Custom" and make the fields editable.

**Comment by sceuick** [comment]
I'm happy to throw a button next to the list of presets that is only enabled when `Use Preset = true` and the selected preset is not `Service or Fallback`.
I'm not sure what the wording should be on the copy. As stated above, clicking the button should just copy the preset settings to the `chat.genSettings` and unset `chat.genPreset`.

**Comment by malfoyslastname** [comment]
- Users should be able to edit the active preset on the fly from within the chat page (whether the changes should be unique to the current chat or applied to the preset is up for discussion)
- Users should be able to edit the active character on the fly from within the chat page

Very important features that users love about Silly. Liable to work on them if no one gets to them first, will send notice here and on Discord if I do.

**Comment by sceuick** [comment]
> * Users should be able to edit the active preset on the fly from within the chat page (whether the changes should be unique to the current chat or applied to the preset is up for discussion)
> * Users should be able to edit the active character on the fly from within the chat page
> 
> Very important features that users love about Silly. Liable to work on them if no one gets to them first, will send notice here and on Discord if I do.

1. Yup, agreed.
2. Yup, also agreed. Perhaps a toggle for whether it the changes to the character are for "this chat only" vs "edits the base character". Needs _much_ better wording than that though.

**Comment by malfoyslastname** [comment]
just bookkeeping,
@sceuick if i'm correct, point [1] addressed in 0a460f46134124941760f4bbbc1007feb64484cb, point [2] is pending

**Comment by sceuick** [comment]
This is now implemented.
