### ISSUE TITLE
Can't scroll when want to create new chat

### ISSUE THREAD

**Issue by Alfiandrr** [agnaistic/agnai#149]
I'm sorry in my phone when I'm going to create new chat, I can't scroll down to press create button, its look stuck, I'm sorry if I attach 2 bugs at same time🙏🏻 hope you not problem with that, thank you in advance🙏🏻
![20230405_104608](https://user-images.githubusercontent.com/129920632/229976182-341088ea-44b2-486d-b23c-f763ac2d404a.jpg)

**Comment by sceuick** [comment]
Ooh, nasty. I'll sort this out quickly. Thanks.

**Comment by sceuick** [comment]
Just deployed a fix. Try refreshing and hopefully the issue is fixed. Sorry about that!
