### ISSUE TITLE
Bug: Singular chats stop producing replies

### ISSUE THREAD

**Issue by Cheesestrings2929** [agnaistic/agnai#150]
I'm not sure what causes this, but so far 2 of my many chats have stopped loading replies. I can try whatever I want, but it won't even show the Queue, even though other chats work perfectly fine at the same time. It's frustrating because this happens when I'm already invested in the plot of a chat.

**Comment by sceuick** [comment]
Do you get any errors in the network tab or console?

**Comment by Cheesestrings2929** [comment]
> Do you get any errors in the network tab or console?

No not at all, although I managed to fix it by exporting the conversation into a new one

**Comment by sceuick** [comment]
I'll close for now until I get some more info to work from. Feel free to re-open if you can reproduce it.
