### ISSUE TITLE
Encrypted chats and characters

### ISSUE THREAD

**Issue by acidbubbles** [agnaistic/agnai#155]
So, that's probably a more complex one, but I think it's worth discussing since there's a high probability of conversations to be eventually either hacked, or a vulnerability might make them available by mistake, or someone has access to MongoDB.

There are multiple ways to approach this, and this issue is to start discussing them.

- Option 1: No encryption (current)
- Option 2: Encryption using a server key (only protects against MongoDB access)
- Option 3: Server encryption using a user key (tricky, since you need that key to be in MongoDB too, but at least this avoid selecting incorrect  documents since you'd also need to load the wrong user to decrypt them)
- Option 4: Client encryption (using a password-derived key, which means changing password requires re-encrypting everything)

I think the option 4 would be great, since it would make the whole system much more secure. I think only some fields, such as the messages, character name and fields should be encrypted.

What do you think? Am I being paranoid?

**Comment by acidbubbles** [comment]
Here's what GPT-4 suggests for Option 4:

To achieve this, you can use client-side encryption, where the encryption key is derived from the user's password or some other user-provided secret. Here's a general outline of the process:

User authentication: When the user signs up or logs in, authenticate them using a secure password hashing algorithm like bcrypt.

Key derivation: Derive an encryption key from the user's password or secret using a key derivation function such as PBKDF2, scrypt, or Argon2. This will generate a unique and secure key based on the user's input, which can be used for encryption and decryption.

Encrypt data: Before storing the user's data in MongoDB, encrypt it on the client-side (in the user's browser or device) using the derived encryption key. You can use a symmetric encryption algorithm like AES-256-GCM for this purpose. Make sure to also generate and store a unique initialization vector (IV) or nonce for each encrypted data piece to ensure the encryption is secure and non-deterministic.

Store encrypted data: Store the encrypted data and the associated IV or nonce in MongoDB. You don't need to store the encryption key in the database since it can be re-derived from the user's password or secret.

Decrypt data: When the user wants to access their data, re-derive the encryption key from their password or secret using the same key derivation function. Then, decrypt the data on the client-side using the derived key and the stored IV or nonce.

This approach ensures that only the user who knows the password or secret can decrypt their data. The server and the database only store encrypted data, and they never have access to the encryption key. This provides a higher level of security for sensitive user data.

However, it's important to note that this approach comes with a trade-off: if the user forgets their password or loses their secret, they will lose access to their encrypted data, as there's no way to recover the encryption key. You might want to implement a secure recovery mechanism or inform users about the importance of backing up their secrets.

**Comment by acidbubbles** [comment]
Actually the key should be sent to the API so the server can fetch the data necessary to load books and conversation data. The point here is not to have the key on the client, but rather to protect from erroneously using the wrong key (you can't if you don't have it) and from accessing raw data from the database (same).

The implementation could forward the derived key in an http header, and stored on the browser. Now either the key is only kept in memory, which means the user needs to enter their password every single time, or the derived key is kept in local storage or a cookie, which adds another risk of XSS. But then again, you need the key And the raw data, and if you have successfully used XSS it's easier to exfiltrate the data and not just the key... So, meh.

Long story short, keeping a derived decryption key in local storage, sent along with api calls, would add a major layer of protection to user data, for some additional complexity and the inability to restore forgotten passwords if you enable that feature (unless you have another mechanism for that)

**Comment by sceuick** [comment]
This would likely be prohibitively computationally expensive. The API deals with large volumes of data quite frequently that would need to be decrypted. The API at the moment handles several hundred concurrent users on very minimal amount of hardware.
 It would also be very non-trivial to implement. The effort/value of doing this and the cost required to support it makes me very unlikely to consider implementing something like this any time soon. There are other annoying things to consider with this: group conversations, backwards compatibility, etc.

**Comment by acidbubbles** [comment]
Right, this would probably only be for specific, personal chats. It makes no sense for shared chats. As for the computation, I'm not sure, it's not so much worse than https. But then again, I accept your conclusion (at least for now), and I agree it's definitely not simple to implement. I'll think this through later and I might try and suggest something eventually, because I think that this data is worth protecting, especially for shared servers.

For now, thanks for your feedback, I appreciate it :)
