### ISSUE TITLE
Broken navigation menu

### ISSUE THREAD

**Issue by teasouse** [agnaistic/agnai#163]
After the recent update menu button links don't work.

**Comment by sceuick** [comment]
Which button links? A screenshot may help. Thanks.

**Comment by teasouse** [comment]
![image](https://user-images.githubusercontent.com/10737240/230569306-f18cc441-269c-440d-8190-38afd03c08ba.png)
I figured out It's stopping working after I click on settings

**Comment by teasouse** [comment]
I figured out It's stopping working after I click on settings.
![123](https://user-images.githubusercontent.com/10737240/230570279-a10e2e52-9042-43bd-b1db-b63a9f72c7bc.jpg)

**Comment by sceuick** [comment]
I can't seem to reproduce this locally or on the live version.
I can't reproduce it on iOS either.

**Comment by malfoyslastname** [comment]
Open devtools and check if the console prints any errors when you click on Settings.

**Comment by teasouse** [comment]
[1680857385034.log](https://github.com/luminai-companion/agn-ai/files/11177533/1680857385034.log)
Here's the log from devtools console

**Comment by teasouse** [comment]
Everything seem to work fine only after the clean install

**Comment by malfoyslastname** [comment]
Per the README, run `npm run deps` every time you update agnai.

**Comment by teasouse** [comment]
> Per the README, run `npm run deps` every time you update agnai.

I did it the first time and the second time to be sure. Didn't help.

**Comment by malfoyslastname** [comment]
Good to know, we must find the cause of this upgrading issue.

**Comment by sceuick** [comment]
I wonder if you may need to log out then log back in again?
I just did a fresh clone and install and encountered unexpected behaviour, but was getting `401`s constantly due to having a cookie with a JWT, but the JWT was signed with a different secret. I probably need to handle automatically logging out the user if the API responds with 401.

**Comment by teasouse** [comment]
> I wonder if you may need to log out then log back in again? I just did a fresh clone and install and encountered unexpected behaviour, but was getting `401`s constantly due to having a cookie with a JWT, but the JWT was signed with a different secret. I probably need to handle automatically logging out the user if the API responds with 401.

I clear cookies every time I upgrade it, but that didn't help. I just tried to run it again and noticed pic related. No Idea what it means, but I've never had that error before the last update. Freshly installed one doesn't have that either.
![image](https://user-images.githubusercontent.com/10737240/230621777-27628be6-2bc6-4c2d-abfd-dd001b11df72.png)

**Comment by teasouse** [comment]
> I wonder if you may need to log out then log back in again? I just did a fresh clone and install and encountered unexpected behaviour, but was getting `401`s constantly due to having a cookie with a JWT, but the JWT was signed with a different secret. I probably need to handle automatically logging out the user if the API responds with 401.

I clear cookies every time I upgrade it, but that didn't help. I just tried to run it again and noticed pic related. No Idea what it means, but I've never had that error before the last update. Freshly installed one doesn't have that either.
![230621777-27628be6-2bc6-4c2d-abfd-dd001b11df72](https://user-images.githubusercontent.com/10737240/230622834-0b2e6b1c-9486-4a8a-ba3a-e95ab40fd5f5.png)

**Comment by sceuick** [comment]
The hard drive is full. You'll need to delete some things to free up some space.

**Comment by teasouse** [comment]
> The hard drive is full. You'll need to delete some things to free up some space.

Lol, that is certainly not true.
![image](https://user-images.githubusercontent.com/10737240/230626116-85b836ca-d61f-4766-8032-0f1342ac4c8f.png)

**Comment by sceuick** [comment]
I'm not sure what else to make of `No space left on device` then.

**Comment by teasouse** [comment]
> I'm not sure what else to make of `No space left on device` then.

Some paranormal shit happening.

**Comment by sceuick** [comment]
I haven't had any other reports of this.
Is this still happening to you?

**Comment by teasouse** [comment]
> I haven't had any other reports of this. Is this still happening to you?

No issues with updating after clean install. Everything works fine.
