### ISSUE TITLE
error on token front- ? 

### ISSUE THREAD

**Issue by beauxism** [agnaistic/agnai#165]
![image](https://user-images.githubusercontent.com/130204165/230730458-2a4c962d-bef3-427e-ab3a-767323082563.png)
hi all, im not sure whats wrong with my api key, but everytime i go to talk to the ai it doesnt work, it keeps saying this

i'm not very good at working with this stuff, im very new and im sorry if i dont explain the issue very well

edit: attached another error message im getting, im super confused 
![image](https://user-images.githubusercontent.com/130204165/230731360-eccebba4-ccfe-424a-b4db-58e80aac8e24.png)

**Comment by sceuick** [comment]
Sorry you're having issues. I'll look into it.

**Comment by sceuick** [comment]
I have a suspicion that your character definition might be too large.
I'll add a check for this kind of case as well as showing the token counts in various places.

**Comment by beauxism** [comment]
Thank you so much!

**Comment by sceuick** [comment]
Some tweaks have been made to the Novel adapter. Hopefully most of these are resolved.
