### ISSUE TITLE
Code formatting is messed up (GPT-4)

### ISSUE THREAD

**Issue by JimmysDev** [agnaistic/agnai#168]
Hi devs,

I'm having a problem with agnai.chat where, when using GPT-4 to write Python, it messes up the format by not correctly indenting.

![GPT formatting issue](https://user-images.githubusercontent.com/109320523/230790381-dbed47bf-fbb2-4183-9514-d91b32e5ce63.jpg)

I compared the same bot in Tavern and didn't get this issue. Just wanted to rule out an issue with the bot, I am open to the possibility of it being a setup issue however.

![python formatting correct](https://user-images.githubusercontent.com/109320523/230790385-9a7fef3c-ab60-4cf7-80fa-cb7a50b3cd26.jpg)

Thanks for all your work,
Jimmy

**Comment by acidbubbles** [comment]
The problem is caused by this: https://github.com/luminai-companion/agn-ai/blob/18a5ff31d6549465f6023a5b49b0b4d66264e02d/srv/api/chat/common.ts#L109

I'm not sure why this is there, but I would remove the replace completely and only keep the trim. Do you have objections?

**Comment by sceuick** [comment]
Should be resolved now.
