### ISSUE TITLE
Bug: long character descriptions break UI

### ISSUE THREAD

**Issue by malfoyslastname** [agnaistic/agnai#178]
Entering a long description when making a character breaks the character list.
![1681392475](https://user-images.githubusercontent.com/128472336/231773563-e4aae741-24ac-4d9c-911d-f31e5db4697d.png)
![1681392479](https://user-images.githubusercontent.com/128472336/231773573-6e9a1f7e-092b-436f-9bfe-66eb42af1ba4.png)

Proposed possible solutions
- Force descriptions on one line and truncate them when over the limit.
- Reduce description font size, display it under the character name, allow the container to be multiline

**Comment by sceuick** [comment]
Ah, just need to switch to padding instead of height for cards.

**Comment by acidbubbles** [comment]
Probably the same as #175

**Comment by malfoyslastname** [comment]
Note: long chat names do the same.

**Comment by sceuick** [comment]
Should be fixed now. :crossed_fingers:
