### ISSUE TITLE
Data gets wiped every time 'npm install agnai -g' is ran

### ISSUE THREAD

**Issue by ghost** [agnaistic/agnai#180]
Using the npm package version of Agnai, everyting inside node_modules/agnai/db/ is deleted whenever `npm install agnai -g` is ran. It would make sense if the command was advertised to fully reinstall the program, but it says 'install or update' in the readme.

**Comment by sceuick** [comment]
Hey there, this should be fixed in efac688 and published as version `alpha-14`.
It'll wipe it again unfortunately on the next install. The new version creates a folder in your home directory called `.agnai`.
Re-open if the new version is busted as well.
