### ISSUE TITLE
Multi-user room improvements

### ISSUE THREAD

**Issue by malfoyslastname** [agnaistic/agnai#182]
# Multi-user room improvements

## Important bugs

- When invited to a chatroom, it seems like invitees are not able to leave the chatroom until the owner deletes the chatroom, kicks the user, or deletes the character
- if you join a room and then get kicked, you still get notifications

## Features

- OOC chat
  - Users should be able to send messages entirely ignored by the bots and prompt   building
  - There should be a toggle to hide OOC messages in order to have a good view of the RP-only messages
  - OOC mode should be the default to avoid accidentally sending RP messages, and because OOC chat is likely to be more common than RP chat (experience speaking)
  - The toggle should be easily accessible, preferably in one click outside of the dropup
  - OOC messages should be visually distinct from RP messages to make it easier to visually parse chaotic chatrooms. Suggested: slightly faded colors, while maintaining readability ([quick and dirty example](https://user-images.githubusercontent.com/128472336/232073251-10b8c7bf-e552-46ad-8b21-baec9c363fb8.png). Suggesting adding different background color on top of that. Note to self: overuse css IDs to make userstyle writers' life easier)
  - Possible implementation pitfall to watch out for: sending an OOC message while a response is loading should not clear the message loading dot animation

- It's often desirable for multiple people to send messages before the bot sends its response (experience speaking). There's multiple ways this could be accomplished but I recommend this one:
  - "Manual mode" where the room creator manually chooses when to generate a bot message **(This feature overlaps with the work I've started on multi-bot chatrooms, if someone else is looking at this we should align)**

- Avoiding people talking over each other (a group must know who is speaking next in order to not type their message for nothing):
  - Something which could help is a typing indicator, that differentiates whether the person typing is writing a RP message or an OOC message (this is not the best solution, because people might be typing first as OOC, then when they're finished switch the toggle to RP at the last moment)
  - Optional queue system
    - Users should be able to freely join and leave the queue
    - Should users be automatically re-queued, or have to re-queue every time they want to participate? Undecided.
    - Spontaneity is sometimes necessary so perhaps the queue should be indicative and not lock users out of sending RP messages? Or this could be a setting.
    - Room creator should be able to skip people's turns if they're unresponsive
    - room participants should NOT be added to the queue by default, lurkers and afkers are too common
  - As a workaround, I've used OOC chat to keep track of who wants to speak next, but it takes a lot of effort.

**Comment by sceuick** [comment]
- OOC Chat: Should these be ephemeral messages or should they be persisted? It'd be less logic if these messages were broadcast to the participants, but never persisted.
- "Manual mode": Yup, sure. Only needs to be a multi-user room feature.
- "{{user}} is typing..." indicators: Yup, this is in the roadmap as well. I'm sure you have some thoughts on how to do this without being too noisy bandwidth-wise.

**Comment by malfoyslastname** [comment]
- "Take screenshot" should be available to participants

OOC chat should be persisted, I would say this is pretty important.
I don't really have thoughts for typing indicators, sorry!

**Comment by malfoyslastname** [comment]
OOC chat pushed
Queue system not a huge priority, but typing indicator is still desired

**Comment by sceuick** [comment]
I believe all of this is pretty much done. Typing indicator and be tracked separately.
