### ISSUE TITLE
Feature request: replace {{user}} and {{char}} in UJB for all compatible adapters

### ISSUE THREAD

**Issue by malfoyslastname** [agnaistic/agnai#183]
Currently, {{user}} and {{char}} are replaced in the UJB inside the Claude adapter, but not the OpenAI adapter. This should be replaced before the UJB reaches the adapter.

**Comment by ewof** [comment]
done in #138

**Comment by sceuick** [comment]
Oh, sorry @elwolf6. I just yaught this into dev with a fix for the missing `top_p` in OpenAI payloads.
