### ISSUE TITLE
NPM Package: Character avatar images break/are deleted every time Agnai is restarted

### ISSUE THREAD

**Issue by ghost** [agnaistic/agnai#185]
Every time I restart Agnai, all my characters have their avatar images removed, leaving their icons to look like this
![image](https://user-images.githubusercontent.com/67460148/232178909-a553909f-74d8-446e-85d7-2d96baf44ce2.png)
This is on version v0.1.0-alpha-14

**Comment by sceuick** [comment]
Hey there, I implemented a fix for this in alpha-14, but it still would have occurred when upgrading to alpha-14.
Hopefully it doesn't occur when upgrading to the next version.

**Comment by sceuick** [comment]
Ah, actually I think I misread this. I'll look further into this.

**Comment by sceuick** [comment]
This should now be fixed in `alpha-16`.
