### ISSUE TITLE
Preamble capped off

### ISSUE THREAD

**Issue by rondlite** [agnaistic/agnai#19]
- Suggestion:
Should preamble length be taken off the max tokens?
At the moment after  a while the preamble is not part of the chat anymore and pinky lost the brain ..

**Comment by sceuick** [comment]
Are you referring to the `createPromptSurrounds` values?
Afaik the `pre` and `post` should always be in the final prompt. If it isn't, that's a bug.

**Comment by rondlite** [comment]
I don't know exactly what part it is, i think preamble in prompt.ts, this cut off at some point till only chat is left.
The part with the persona and scenario.
I guess that preamble size is not taken into account, I am not sure.  It is a bug for sure.

**Comment by sceuick** [comment]
The prompt creation is intended to:
- build the `preamble`: The persona, greeting, scenario and sample chat.
- build the `postamble`: Generally just `"BOT_NAME:"`
- fetches the message history by `createdAt` descending
- iterates over the messages, appending them to the context until the `pre + history + post` context the `maxContext` token size is reached.
- combines the 3 and returns them

This is working in my debugger at the moment for guests and users.

**Comment by rondlite** [comment]
I will test on the client side, I was now looking at what comes in at KoboldAI, this output might be capped.
Will let you know if it wasn't my oversight..
