### ISSUE TITLE
Temperature not changing when using the proxies?

### ISSUE THREAD

**Issue by cc240b** [agnaistic/agnai#194]
When using any of the reverse proxies with Agnai (I use the live version) all of the regens keep giving me similar messages as if the temp was stuck at 1 or lower, even when I change it to the maximum value possible.
I tried using my own key on Agnai and using the proxies on Franken Tavern and the temperature was clearly working as intended, so there's something about this particular combination that seems to break it.
I'm not sure if it's just the temperature either or if any other settings are stuck too, but temp was the easiest one to test.

**Comment by sceuick** [comment]
This will be virtually impossible to verify. I know little-to-nothing about the proxies. I assume whatever Agnai is doing is likely vastly different to whatever the other proxy consumers are doing. There is no built-in support for any proxies in Agnai so it's likely the mechanism being used by Agnai has a bug downstream.
