### ISSUE TITLE
Small feedback

### ISSUE THREAD

**Issue by CncAnon1** [agnaistic/agnai#2]
Small UI thing, I think it'd be better if the conversation header would actually stick on the top instead being on the bottom until you start writing messages:
![image](https://user-images.githubusercontent.com/117792279/223153465-a6324b18-6bdd-4639-9b2f-b135f3e60ab5.png)

Also, regarding the adapters. I've looked at the code and it looks like it's currently centered around text-based completion, which is fine since most services are like that. But are you planning to maybe change it to allow for easier integration of OpenAI Turbo? As far as I know by the code, it's possible right now, but a lot of code will have to be reimplemented in that adapter specifically - getting the messages, tokenizing them (Turbo model has a different tokenizer), also checking the context (because of a different tokenizer + OpenAI's max token context is 4096).

Also I think that if implemented, Davinci and Turbo should be two fully separate adapters, since Davinci is really close to other adapters in how it'll work, but Turbo is completely different.

Anyway, I'll try to add Davinci first and then see if I hack around Turbo support just for testing (I doubt it'll be PRable since I suck at webdev)

**Comment by sceuick** [comment]
Thanks for the feedback! I'm going to be undertaking some re-theming over the next day or two. I'll look at sticking the conversation title at the top.

As for OpenAI, I hadn't looked into it yet. I'm more than happy to make sure it can be supported.
We can add `max_context_length` to the generation settings. Shouldn't be too much effort to add it there at all.

**Comment by sceuick** [comment]
I've tweaked the header and added `max context length` to the generation settings/presets.
![image](https://user-images.githubusercontent.com/60520115/223325365-bfd92744-2490-4aa6-b1b1-609e1083c4d6.png)
![image](https://user-images.githubusercontent.com/60520115/223325426-1f28b7d9-1709-468b-afb7-fce3ae557fb6.png)

**Comment by ewof** [comment]
idk if it's just me but whenever i import a character with both json file and a png it doesn't set the avatar of the character to the png i set and i have to edit it to set the avatar. also all avatars users/characters seam to "fit" the image into the space it'd be better if it was fill so there were no black boxes

**Comment by ewof** [comment]
also delete buttons for presets would be very nice

**Comment by sceuick** [comment]
For about a day or three I had broken image uploading. I'll make sure it's also fixed for character importing.
I'll have a play with the `object-fit` settings for the avatars. :+1: 

For about 2-3 days avatar uploading was broken. I've pushed a fix, but I may have missing the fix in character imports. I'll double check.

**Comment by sceuick** [comment]
Yeah, avatar uploads on imports was definitely broken and always was.
It's fixed now and `object-fit` on avatar images is now `cover`.

**Comment by CncAnon1** [comment]
@elwolf6 thanks for adding openai support, but is there any reason you included the anti-NSFW prompt here by default? https://github.com/luminai-companion/agn-ai/blob/97f5a61393fe03550f0ef445572564cf8ddb1301/common/presets.ts#L87 It actively prevents characters from interacting in any NSFW way.  It's good that you added a way to modify it, but the default seems a bit weird.

**Comment by CncAnon1** [comment]
Also, are you planning on creating a community on Discord or some other platform, e.g. Matrix?

**Comment by sceuick** [comment]
I'm working that out at the moment.
For now you can contact me directly on Discord sceuick#0414.
Once I have an update, I'll put it on the Readme.

**Comment by sceuick** [comment]
@CncAnon1
The discord for Agnai will be at the luminai-companion org
https://discord.gg/efcb48jk

**Comment by sceuick** [comment]
Most of this is resolved now. There is also a link to the discord in the readme now.
