### ISSUE TITLE
 Feature request: Option to edit stop sequences.

### ISSUE THREAD

**Issue by gtaltatra** [agnaistic/agnai#201]
Messages get cut off far too often compared to tavern, can we edit them? 
Also, in the meantime (or if you wont implement this), could you tell me what do I need to edit manually for this for openai adapter? For claude I guess I need to change this code
```
const stops = new Set([
    `\n\n${char.name}:`,
    `\n\n${username}:`,
    `\n\nSystem:`,
    ...members.map((member) => `\n\n${member.handle}:`),
  ])
```
in claude.ts and rebuild?

**Comment by sceuick** [comment]
you can create a top-level `settings.json` file that looks like this:
```json
{
  "baseEndTokens": ["System:", ...]
}
```
This will add your own stop tokens without having to modify code.

**Comment by gtaltatra** [comment]
Will this apply to all adapters? 
```
{
  "baseEndTokens": ["System:", "\n\n${char.name}:", "\n\n${username}:"]
}
```
Like this?

**Comment by sceuick** [comment]
It'll apply to all adapters. I don't believe it supports placeholders though. Probably a good idea to add them.

**Comment by gtaltatra** [comment]
Does it support line breaks at least? 
>I don't believe it supports placeholders though

So, if I use this file to remove ${username}, I wont be able to keep {char.name}? Is there an alternative way?

**Comment by sceuick** [comment]
I'll add support for `{{char}}` and `{{user}}` placeholders. And yes, line breaks are supported.

**Comment by gtaltatra** [comment]
Ok, thanks

**Comment by malfoyslastname** [comment]
I highly doubt those stop sequences are what's causing your messages to appear cut-off
