### ISSUE TITLE
Request: Change Claude's prompts sent to the API to be "Human" and "Assistant".

### ISSUE THREAD

**Issue by GuyfromGit** [agnaistic/agnai#204]
The way Agnai currently sends prompts to Claude's API involves using "{{char}}" and "System:".
However, according to Anthropic documentation on prompt design, the prompts sent to the API must contain the following: "Prompts sent via the API must contain \n\nHuman: and \n\nAssistant: as the signals of who's speaking."
As such, I request that the way prompts are sent be changed to reflect this, as this should improve the replies received from Claude because of better prompting.

Here is the documentation I'm quoting:
https://console.anthropic.com/docs/prompt-design

**Comment by malfoyslastname** [comment]
Author of the Claude adapter here. I'm aware of what the documentation says, but I've tested the current method on Claude 1.2 to perform excellently. I'm open to using the documentation's condoned formatting BUT I'd like to see some side-by-side experiments (with multiple swipes for each test case) rather than taking the documentation at its word before making any switch as the current quality is already tremendous.

**Comment by malfoyslastname** [comment]
To add on to that, using the models' preferred formatting may force the user to buy into RLHF which may be undesirable for roleplaying purposes.

The OpenAI chat models force prompts into a specific formatting which has been trained/tuned/RLHF'd to act as an assistant and refuse certain commands. Back in January and February when a few raw text ChatGPT models were "unofficially" available, it *seemed* that by simply not using the official message formatting, you would bypass the ChatGPT RLHF pretty effectively.

(Note: the above is an untested hypothesis. The official message formatting was unknown at the time, so it is unclear if the leaked ChatGPT models were simply unfiltered, or if not using the official formatting was what caused them to be unfiltered.)

Hence, there is a possibility that following the formatting condoned by the documentation may not be the best way for agnai. Experimentation is needed.

**Comment by GuyfromGit** [comment]
I did some tests with Human and Assistant by modifying the Claude.ts file
Suffice to say, the results in Agnai weren't good
My current jailbreak didn't work, since the AI thought that it was responding as the AI instead of as the character
In the end, unless a proper way is made to put words directly into the AI's "mouth" as the Assistant is found, the way that Agnai does its better for itself. 
With that in mind, I would like to ask you to conclude my request by closing it.

**Comment by sceuick** [comment]
Thanks for looking into it.
