### ISSUE TITLE
UI: bug: avatars can go over the chat header

### ISSUE THREAD

**Issue by malfoyslastname** [agnaistic/agnai#209]
![img](https://cdn.discordapp.com/attachments/1092431307189010532/1098316177333309541/2023-04-19_21.35.38_agnai.chat_5fffa09995ae.png)

**Comment by sceuick** [comment]
Will need to remove the text X overflow and use an ellipsis for the character name and chat title.

**Comment by sceuick** [comment]
This one should be fixed now :crossed_fingers:
