### ISSUE TITLE
UX: Chats get deleted with no warning when deleting a character

### ISSUE THREAD

**Issue by malfoyslastname** [agnaistic/agnai#211]
Very important UX pitfall, need to think how to address it.

Possible fixes:

- Add a warning when deleting a character ("This will delete 3 conversations. Are you sure?")
- Add ability to choose whether to delete conversations alongside the character (what happens if you try to continue chatting in a conversation that you no longer have the character for?)

**Comment by sceuick** [comment]
A warning will have to do. A chat requires a character.

**Comment by acidbubbles** [comment]
PR :) https://github.com/luminai-companion/agn-ai/pull/217

**Comment by sceuick** [comment]
A warning has now been added.
