### ISSUE TITLE
Feature Request: Add support for koboldcpp on local

### ISSUE THREAD

**Issue by ridwanarf25** [agnaistic/agnai#213]
I tried to build agn-ai locally and put mycustom endpoint to koboldcpp  but it can't i think its not yet supported will be great if you add it

Also how do i connect to database so i don't run agn-ai in anonymous-only mode? I did install mongoDB but idk what to do after that

**Comment by sceuick** [comment]
If you don't require auth, but want more storage then using the npm package is probably the way to go.
You can run the local version with JSON storage by setting the environment variable `JSON_STORAGE=1`.

As for mongo, if you used the defaults then it _should_ connect automatically. If you changed the port or set a username and password you'll need to modify some other environment variables:
`DB_PORT=27017`
`DB_HOST=username:password@127.0.0.1`

**Comment by sceuick** [comment]
As for koboldcpp support, I'd need to see API docs for it. If it already has a kobold-compatible API then it should already work.

**Comment by sceuick** [comment]
Pretty sure support for koboldcpp has been available in Agnai for a while now. :crossed_fingers:
