### ISSUE TITLE
Feature request: Make BE send exact prompt/payload back to the FE, then log it to browser console 

### ISSUE THREAD

**Issue by malfoyslastname** [agnaistic/agnai#214]
One feature people like about Silly is the ability to see the exact prompt/payload logged to the server console. This convenience can be replicated on agnai.chat by having the BE send the exact prompt to the FE (perhaps just alongside the generated response), and then logging it to the browser console. Doing things this way requires no additional storage.

**Comment by sceuick** [comment]
The only difference between the client and server side prompts is authed users _might_ have more messages inserted into their prompt. It'd require less bandwidth if the client logged out what it was sending to the server as it's most likely going to be identical.

**Comment by malfoyslastname** [comment]
Right
