### ISSUE TITLE
Bug: On Bad Request the server will crash

### ISSUE THREAD

**Issue by rondlite** [agnaistic/agnai#222]
When a Bad Request error occurs, the server crashes. I think this is due to the next in this line having nowhere to go:
https://github.com/luminai-companion/agn-ai/blob/c740776dbd7c1956a9be28513ade5c6390700c2a/srv/api/wrap.ts#L20

Should the catch not just return a status and a json instead of going to next?

**Comment by sceuick** [comment]
No, there is an error handler middleware. See `app.ts` - a middleware function that takes 4 arguments receives is called when `next` is called with a truth-y value. I don't believe I've personally seen my servers crash on a bad request.

**Comment by rondlite** [comment]
This is what I get in the log, I will investigate what is happening 

```
[api] /app/srv/api/wrap.js:55
[api]     BadRequest: new StatusError('Bad request', 400),
[api]                 ^
[api]
[api] StatusError: Bad request
[api]     at Object.<anonymous> (/app/srv/api/wrap.js:55:17)
[api]     at Module._compile (node:internal/modules/cjs/loader:1254:14)
[api]     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
[api]     at Module.load (node:internal/modules/cjs/loader:1117:32)
[api]     at Module._load (node:internal/modules/cjs/loader:958:12)
[api]     at Module.require (node:internal/modules/cjs/loader:1141:19)
[api]     at require (node:internal/modules/cjs/helpers:110:18)
[api]     at Object.<anonymous> (/app/srv/api/auth.js:8:16)
[api]     at Module._compile (node:internal/modules/cjs/loader:1254:14)
[api]     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10) {
[api]   msg: 'Bad request',
[api]   status: 400
[api] }
[api]
[api] Node.js v18.15.0
[api] node srv/start.js exited with code 1
```

**Comment by rondlite** [comment]
must be my own fault somewhere since vanilla install does not have this indeed..
