### ISSUE TITLE
Feature request: allow all placeholders in UJB

### ISSUE THREAD

**Issue by malfoyslastname** [agnaistic/agnai#225]
It is worth it for users to be able to experiment with moving certain prompt information from the gaslight (preamble) to the ujb (postamble).

This should come with an updated UI that says that all placeholders are allowed.

Note: currently {{char}} and {{user}} are replaced at the adapter level. instead this should be done before the ujb hits the adapter

**Comment by malfoyslastname** [comment]
Will give notice if I start work on this

**Comment by sceuick** [comment]
Labelling as bug due to the UJB placeholders being replaced in the adapter. That might cause bad token counts.
I'm fine with all placeholders being supported in the UJB. I'm wondering if we need to do anything about placeholders being used in the gaslight and the ujb at the same time?

**Comment by sceuick** [comment]
Landed this in 747b6d1.
