### ISSUE TITLE
UI: Display the actual name of the generation preset in use instead of 'User Preset'

### ISSUE THREAD

**Issue by ghost** [agnaistic/agnai#232]
Referring to this text in the top right of chats:

![image](https://user-images.githubusercontent.com/67460148/233793215-8219e862-8c7e-4aa2-a923-5206a0363d2f.png)

**Comment by malfoyslastname** [comment]
duplicate of https://github.com/luminai-companion/agn-ai/issues/120
I looked at this before and had trouble figuring out how to get the data where it needs to be.
I might take another look this weekend.

**Comment by sceuick** [comment]
I've landed this in a recent commit 7a52156
