### ISSUE TITLE
Tokenization for OpenAI Turbo model

### ISSUE THREAD

**Issue by CncAnon1** [agnaistic/agnai#24]
Since AgnAI now supports the Turbo OpenAI model, there's a need to add another tokenizer for it as it uses a different tokenizer. There's an NPM package https://www.npmjs.com/package/@dqbd/tiktoken that supports both normal gpt tokenizer (called `gpt2`) and the Turbo one (called `cl100k_base`). Changing the code to use it is quite easy, but I first wanted to make sure you're ok with it - after all, that package uses WASM, so I'm not sure how well will it work for something that's user-facing.

There's one other problem though - Turbo uses a special way of denoting messages, so the token counts are a bit different from just the raw prompt (they're higher) - see [this Jupyter notebook by OpenAI](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb). A simple JS port of that code can look like this:
```js
function count_tokens(encoding, messages) {
    let num_tokens = 0;
    for (var msg of messages) {
        num_tokens += 4;
        for (const [key, value] of Object.entries(msg)) {
            num_tokens += encoding.encode(value).length;
            if (key == "name") {
                num_tokens += -1;
            }
        }
    }
    num_tokens += 2;
    return num_tokens;
}
```

**Comment by sceuick** [comment]
WASM has pretty broad support so that's completely fine. It's definitely best if we use the correct tokenizer for each supported service.
I'll start by doing a small refactor to the token counting logic to call function that takes the `adapter + config + genSettings + text` and returns a `number`.

**Comment by sceuick** [comment]
This is done now. I'm getting a lot of reports about "looping conversions"/"repeated responses".
Hopefully this improves the issue. In my own testing I still observe repeats when using response continuation, but not with regular messages. I'll need to do more testing.
