### ISSUE TITLE
Unchangeable Profile Picture

### ISSUE THREAD

**Issue by OwOLolCat** [agnaistic/agnai#244]
I can't seem to change my profile pic while trying to change it alongside my display name. Not only that, I can't seem to change it afterwards either. This kinda ruins any immersion I get when trying to change pfps and display names for an rp with another bot, and might be a disappointment for anyone wanting to change their profile picture and username for any other reason.

**Comment by Cheesestrings2929** [comment]
It seems to work normally for me, could the picture you're choosing be too small or too big? I think it should work, but maybe it was a temporary bug?

**Comment by sceuick** [comment]
This is probably related to caching. The image gets replaced to save on storage.

**Comment by sceuick** [comment]
I may revert back to not re-using filenames. If I end up using a CDN for assets at the edge, images would have a large TTL and this issue would get worse.
I'll label this as a bug. It's a simple fix.

**Comment by sceuick** [comment]
I think this is fixed now? Please re-open if it isn't.
