### ISSUE TITLE
Some feature requests regarding shared bot usage

### ISSUE THREAD

**Issue by CncAnon1** [agnaistic/agnai#25]
It would be a really nice addition to be able to chat with other people if you're chatting with the same bot, to plan the messages - noticed myself from 4chan "stress-testing".

Another one would be to have some typing status to see what others want to send.

Yet another one - see who's in the room right now

**Comment by sceuick** [comment]
> see who's in the room right now

Yeah, I've been meaning to add a member list to the chat page. I'll chuck "online now" in the backlog as I need to make sure it's done in a fairly optimised way from the outset. Everything is running on a very small instance, but it's coping extraordinarily well.

> some typing status

This would be in a similar vein to "online now". I'll definitely put this on the backlog. Just needs to have the same considerations.


> chat with other people if you're chatting with the same bot

I see what you mean. I can definitely see how this would be helpful. Do you have any ideas how this might look?
I could probably support something like that, but I'd likely make the chat "ephemeral" -- never store it. It'd only be visible be those present and I'd mark it up differently.

**Comment by rondlite** [comment]
just a simple idea.. what if you could send a message to the chat that is not seen by bot but appears in the chat for whoever else joined it, so you can communicate as long as it is within an existing chat, maybe start a message with >> or whatever

**Comment by sceuick** [comment]
There are `OOC` messages now.
As for typing and online indicators, I may tackle this when I do "friend list" and "1:1 friend chats".
