### ISSUE TITLE
Feature request: ability to confirm/change Service and Preset in "Create Chat" modal

### ISSUE THREAD

**Issue by malfoyslastname** [agnaistic/agnai#252]
Would be a huge QoL improvement.
I'm liable to work on this if no one gets to this first, will write a notice here.

**Comment by malfoyslastname** [comment]
seems like @sceuick will be working on this, per discussion on luminai discord

**Comment by sceuick** [comment]
Negative, I was working on editing presets from "Chat Detail -> Generation settings modal".

**Comment by malfoyslastname** [comment]
then i will

**Comment by malfoyslastname** [comment]
this is part of a larger UX proposal for presets/services
https://gist.github.com/malfoyslastname/408de73329ad04f2d5052236037cd89f

**Comment by sceuick** [comment]
The preset is now required when creating a chat.
