### ISSUE TITLE
Can't upload cards

### ISSUE THREAD

**Issue by sha-dx** [agnaistic/agnai#264]
Last night I encountered an issue where I couldn't upload cards.

It would either do nothing when adding one (.png format), or it would say "tavern card accepted", I think it would say "card loaded" and then nothing would happen. If I tried again, the page would freeze, requiring a reload.

I tried restarting the service.
I tried updating with git pull origin dev (as I have in the past) and that broke the install, resulting in "waiting on file changes" errors when I try to run the service.

Sorry I can't be more specific, I don't know exactly what version I was on before. But anecdotally I know of at least 2 other friends that suddenly started having issues with being unable to add cards/having all of their cards corrupted. So this is an early notice about this issue.

I will provide more info if and when I have any.

**Comment by acidbubbles** [comment]
You can open the Chrome Developer console (F12) or whatever browser equivalent you have, it should show you what he problem is (error message in the console in red).

**Comment by sha-dx** [comment]
It turns out my browsercache is full, this does not explain one friend who had the same issue with mongoDB installed, but I will close for now.
