### ISSUE TITLE
Memory books broken by recent update

### ISSUE THREAD

**Issue by BasadoBased** [agnaistic/agnai#265]
Simple problem, on the latest version as of this issue (self-hosted, browser storage), all memory book entries disable themselves when a book is saved. Reenabling them then saving just disables them again. I can confirm that they are actually disabled and don't get fed to the AI. It was functional on the last version I was using which I believe was from about 3-4 days ago. I suspect this commit may be the culprit: https://github.com/luminai-companion/agn-ai/commit/d1e065ec4f244c8f6f3d7ce01ecfc5f8ae3d45f9

**Comment by malfoyslastname** [comment]
my fault, writing fix now.

**Comment by BasadoBased** [comment]
Can confirm this fixed it!
