### ISSUE TITLE
Any way to transfer guest data to MongoDB?

### ISSUE THREAD

**Issue by sha-dx** [agnaistic/agnai#269]
When I initially installed Agnai locally, I didn't put much thought into the need for MongoDB. At the time I didn't really understand why it would be useful or necessary. Fast forward a month and I can't add any cards or modify and characters, I'm guessing my browsercache is full.

The problem is, obviously I don't want to lose all my chats, customized characters and presets.

Is there any way to transfer the data?

As an aside, I installed MongoDB but it's not clear to me how to actually connect it to Agnai from the readme. It just says optional: install MongoDB.

Thanks for the work you are doing,
shad

**Comment by sceuick** [comment]
There isn't a method at the moment except for the manual process of exporting characters/chats/books then importing them once you're logged in.
