### ISSUE TITLE
vital suggestions for improving the project (no)

### ISSUE THREAD

**Issue by ytpk** [agnaistic/agnai#27]
first to first, there is not enough support for tai card format instead of json.
secondly, there is not enough hack in which dialogue examples will not be deleted, aaaandd swipes after the "new generation" of the answer if let's say I got not quite the answer that I wanted, but it is still better than 10 subsequent ones and I want to return to it
I'm really sorry that I can't help the project in any way other than these stupid hackneyed ideas and "bad code" (flashbacks) via chatgpt
Thanks for considering my suggestion and your time!

**Comment by ytpk** [comment]
and also, what about adding "dirty" code for linking cai and agnai like there is a reverse api for accessing characters from there

**Comment by ewof** [comment]
first point just means you want to import the png without using zoltan or something right
second point means you want response swiping right
just want to make sure bc ur shit is hard to read

**Comment by sceuick** [comment]
> Swiping between previous generation

I've thought about this. I can probably do it with some caveats. I don't want to "retrain" (in the database or local storage) the previous generation as the "retry" feature is used _a lot_. I can probably keep the previous generations in application state (they'd disappear after navigating away or refreshing). I'd need to think about the flow for "swiping" and when to confirm the "edit". The main concern here is group chats. 

> Tavern Card (png) support

This is on my backlog, but I haven't prioritised it. I'd prefer to support the feature entirely on the front-end which I think it can be.

> Import directly from C.ai

I'm not sure about this. I support importing their "JSON" format, but I'm not sure I'd want to directly call their API. This seems like a good solution for a chrome extension or Tampermonkey script instead.

**Comment by sceuick** [comment]
I've added these to the backlog. I'll close this issue and track them on my project board.
Thanks for the submission.
