### ISSUE TITLE
Bug: Memory book automatically turns off all entries

### ISSUE THREAD

**Issue by ghost** [agnaistic/agnai#270]
Memory book automatically turns off all entries for some reason when reopening memory book.
<video src="https://user-images.githubusercontent.com/130247549/234740906-07f8e8b6-04c8-4487-987b-93529e427d9a.mp4" controls="controls" style="max-width: 730px;"></video>

Same happens when editing memory book from chat menu.
<video src="https://user-images.githubusercontent.com/130247549/234742541-0e7de40b-ef22-4876-9e93-c9eadfe2ce3f.mp4" controls="controls" style="max-width: 730px;"></video>

It appears that bots cannot access the memory book at all because of this. I am using agnai.chat.

**Comment by sceuick** [comment]
I believe this ought to be fixed now. The fix was undeployed until a few hours ago.
