### ISSUE TITLE
BUG: Import character using tavern card stuck

### ISSUE THREAD

**Issue by ahmed-elj** [agnaistic/agnai#274]
After importing 10 or more characters, the import button get stuck clicked while nothing happening, i select a character card and it say tavern card accepted,
i tried to refresh the page, and delete a character and it can import one new character only and it worked, so it's like a limit to 10 characters
it work fine with json files.

**Comment by acidbubbles** [comment]
I had the same issue once but on mobile... I found a few cases where errors would be silent (try catch with non-awaited promises). #262 improves on that.

**Comment by ahmed-elj** [comment]
Thanks for the fix,  (out of context note: your PR doesn't set the image of the character and i can't seem to modify it)

**Comment by acidbubbles** [comment]
@lorffine you're right, I'll fix it :)

**Comment by sceuick** [comment]
Fingers crossed this is fixed after merging #262 ?
