### ISSUE TITLE
Feat: Character tags filters

### ISSUE THREAD

**Issue by acidbubbles** [agnaistic/agnai#277]
So, it's extremely similar to favorites (#216). Assign tags to a character, and add a list of toggles to show or hide them.

1. With too many characters, you may need more than just favorites. (a tag for test characters for example)
2. You may want to hide some characters when people are around (NSFW tag)

Implementation would include:

1. Show the tags in the list view (in the cards maybe)
2. Add a filter drop down to hide tags (all shown by default)
3. Something to edit the tags in the characters edit page

**Comment by sceuick** [comment]
Yeah, pretty fair idea.
As long as the filtering is done client-side I can't see a problem with it.

**Comment by acidbubbles** [comment]
Yes. I'd also like to use this feature for "archived". I'm thinking of a special tag that is hidden by default, except when explicitly selected.

This way I can get rid of unwanted characters without having to delete the chat history.

**Comment by acidbubbles** [comment]
In progress: https://github.com/luminai-companion/agn-ai/pull/296

**Comment by acidbubbles** [comment]
Ready to review in #296
