### ISSUE TITLE
Suspicious/Bad responses from Horde

### ISSUE THREAD

**Issue by emmapookie** [agnaistic/agnai#279]
what is happening 💀 i can’t even describe the bug it’s just so funny/confusing, i’ve never used github before so sorry in advance if i’m doing everything wrong or should be posting this somewhere else. also i admit that i spend a shit ton of time on this site i’m not even gonna try to defend that i’m just incredibly confused 
<img src="https://user-images.githubusercontent.com/132167030/235322026-eb0a9eb2-fec2-4f97-8797-8d5a0db8fea2.png" height=400 />
<img src="https://user-images.githubusercontent.com/132167030/235322029-4a479236-4708-469d-8bf2-d939d45fcdf3.jpeg" height=400 />
<img src="https://user-images.githubusercontent.com/132167030/235322030-3c1634b8-198c-48b3-8f6a-52b0f0e36039.jpeg" height=400 />
<img src="https://user-images.githubusercontent.com/132167030/235322033-c6fe0253-b163-4e4c-ae82-1b46b928a338.jpeg" height=400 />
<img src="https://user-images.githubusercontent.com/132167030/235322034-1e4c7055-d57c-42ed-a229-8f2ab93d739e.jpeg" height=400 />

**Comment by sceuick** [comment]
Hi there, this is caused by bad actors "contributing" to Horde.
To mitigate this issue it is highly recommended to enable `Use Trusted Workers Only` in `Settings -> Horde`.
The Horde devs have acted quickly to mitigate this issue.

**Comment by chroniclnsomnia** [comment]
the fucking among us
