### ISSUE TITLE
"Database not yet initialized"

### ISSUE THREAD

**Issue by RossAscends** [agnaistic/agnai#28]
my setup: 
win 10, python3.9, 
manual install so..

git cloned the repo,
(mongoDB is not installed on my end)
'npm install' inside a conda env, 
'npm run start:win'

it loads but seemed to be some fishy warnings or errors midway through.
it does compile and the servers runs. 

but when i try to chat i get this 500 error regardless of what API i try to use: 

"database not yet initialized"
mentioned codelines: 
getDb @client.js :27
db @client.js :32
obtainLock @lock.js :14
guest-msg.js :24
wrapped @wrap.js :12
layer.handle @layer.js :95
next @route.js :144
Route.dispatch @route.js :114
Layer.handle [as handle request] @layer.js :95
index.js: :284.15

...ideas?

**Comment by sceuick** [comment]
I think I see the issue. Guest messages aren't meant to try and obtain a lock. I'll push up a fix.

**Comment by RossAscends** [comment]
thanks for the quick reply. I think this front end has huge potential. 

Different question, but where are the user settings and character/chat data stored? I deleted the entire repo directory once to try installing again, but when i came back to the new instance, all the settings were still there.

**Comment by sceuick** [comment]
Fixed in e321100.

For guest usage all of your data is stored in the browser using local storage.
In the developer tools, head to Application tab -> Local Storage. It'll probably be under http://localhost if you're running locally.

**Comment by RossAscends** [comment]
Ok that solved the 500 error, but a new one comes now. 


-- when using OAI API 

"IV not found"
decryptText util.js :32
handleOAI openai.js :58
guest-msg.js :42
task_queues :95
wrap.js :12 

-- when using Horde API: 
the chat reply comes through, but I get the "database not yet initialized" error again. 
getDB client.js :27
client.js :32
chats.js :43
guest-msg.js :66

**Comment by RossAscends** [comment]
further testing with my local Kobold server

chat attempts give an "connect ECONNREFUSED 1:5000" in the browser window (my server is running on localhost:5000)

agnai serverlog shows the same error as with Horde (500, "database not initialized", with same code lines mentioned)

**Comment by sceuick** [comment]
You may need to go to your "Settings" page in the UI and set the `koboldUrl` to `http://127.0.0.1:5000`

**Comment by RossAscends** [comment]
when i got the abovementioned errors i had it set as:

 "http://localhost:5000/api" (setting used in TAI, which works for it) 

putting it as "http://localhost:5000" at first seems like it's working, but soon gives in-browser error "getaddrinfo ENOTFOUND localhost" error..apparently from kobold. 

changing it to "http://127.0.0.1:5000/api" ..i get error: "NOT FOUND"

setting it to "http://127.0.0.1:5000/"  it works properly. 

might be worth it to mention to only use strict IP addresses, and to not include /api/ in the Kobold server URL!

**Comment by sceuick** [comment]
That's a good idea. I'll either clarify in the UI that no path is required or remove it server-side.

**Comment by sceuick** [comment]
I'll close for now. Thanks for raising the issue!
