### ISSUE TITLE
NovelAI image generation doesn't work anymore

### ISSUE THREAD

**Issue by contyk** [agnaistic/agnai#280]
As of some recent update, NovelAI-based image generation doesn't appear to work anymore, just spinning forever.  My token is current, confirmed on the text generation settings page, and I can use NovelAI to generate text content.

However, the image settings page claims that "You do not have a valid NovelAI key set. You will not be able to generate images using Novel."; that is simply not true.  I do not see any other setting specifically for this.

I also believe this used to work fine maybe just a week ago.

**Comment by sceuick** [comment]
Hey there, are you experiencing this as a guest user or logged in?

**Comment by contyk** [comment]
As a guest.

**Comment by sceuick** [comment]
I believe I released a fix for this yesterday.

**Comment by contyk** [comment]
Not sure if the fix is supposed to be included in the latest container images but those still report I don't have a valid NovelAI key set under the image generation setting, despite it being confirmed as valid on the text generation page.
