### ISSUE TITLE
Allow generation when the conversation is empty

### ISSUE THREAD

**Issue by contyk** [agnaistic/agnai#281]
"Cannot retry: Not enough messages"

While the message is clear, I wonder why that is?  Why not just submit the same prompt we sent before getting this one, initial response?

As a workaround, I can copy my initial message, delete everything and send it again, but it just feels rather pointless when I could just regenerate it like at any point later on.

**Comment by sceuick** [comment]
Hey there, this was a limitation from the early days that could potentially be removed now.

**Comment by sceuick** [comment]
I have this implemented. It'll be in the next release.
