### ISSUE TITLE
RFE: Per chat user personas

### ISSUE THREAD

**Issue by contyk** [agnaistic/agnai#282]
Instead of having one global profile, it would be neat if the user could define or choose one per chat.  Maybe even with their own character-like definitions, making the overall roleplay experience quite a bit richer.

Currently one can change their name (and avatar, if desired) before engaging in a new chat, and provide some context for the character they are playing in the scenario, but having a library of predefined player characters would make it neater.

Or perhaps all this could be unified and the user could choose one of their existing characters as being their acting character in an interaction with another?

Willing to brainstorm more in this ticket!

**Comment by sceuick** [comment]
Hey there,
"Per chat" would likely be a little too much extraneous data (mainly images). I was considering allowing users to create multiple profiles and be able to switch between them freely within a conversation. Your messages should 'remember' which profile was used to create a message.
This needs a bit more planning, but hopefully that'd be a drastic improvement.

**Comment by contyk** [comment]
Per message is even more granular than what I'm suggesting but that's great.  One could play multiple people, too.  Although in that case it would also be useful to "send" a message without actually sending it to the AI, e.g. when the character is observing you talking to the other you and such.

**Comment by sceuick** [comment]
"Character impersonation" landed today. Click on your name at the bottom of the navigation menu to impersonate a character when chatting.
