### ISSUE TITLE
Chat UI Broken in phones.

### ISSUE THREAD

**Issue by DHAn0n** [agnaistic/agnai#283]
So yeah, with a recent update (1-2 weeks ago?) the chat UI seems broken, you cant change the chat setting nor the generations settings, also the bar gets stuck in the top of the chat instead of going down like before.

**Comment by sceuick** [comment]
Which model phone and which browser?

**Comment by severedisrepair** [comment]
I have the same issue, except on PC, Brave browser, [Version 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit)]. If I open chat settings or generation settings, I can't scroll down to save settings, instead, the chat in the background scrolls. Same for trying to start a new chat. Firefox seems to work fine, though.

**Comment by DHAn0n** [comment]
Huawei Honor8X
Chrome 101.0.4951.61
Firefox 106.1.0

It happens just like the guy above, but in the both browsers, it was fine before that update but now it gets almost unusable.

**Comment by sceuick** [comment]
I hopefully have a fix for this coming in a fairly big release coming today.
