### ISSUE TITLE
Generated responses often cutting out halfway through a sentence / request for edit capability

### ISSUE THREAD

**Issue by ghost** [agnaistic/agnai#288]
After using this for a few days using default settings although the quality of the replies is generally high, I have noticed the responses often cutting off halfway through a sentence.

I have a related enhancement request.
It would be incredibly helpful to have the capability to edit a bot reply and then use that text in the context.
This would help address the issue above, but it would also be helpful if the bot is struggling to respond well in a particular situation, allowing you to edit enough to get it past the problem.

It would also allow dealing with an unrelated problem where the bot starts responding on behalf of you, sometimes holding the entire conversation with itself.  Being able to edit this part out as needed would help keep it flowing.

**Comment by sceuick** [comment]
Hi,
You can enable chat editing using the menu at the top right of the chat screen. This will allow you to edit and delete messages.
The responses cutting off is related to the `max tokens` in the generation settings. You can increase this, but if you're using Horde it may result in slower response times.

**Comment by ghost** [comment]
Fantastic, many thanks for the quick follow-up.  Much appreciated, will give that a try.
    On Tuesday, 2 May 2023 at 04:17:47 BST, Sceik ***@***.***> wrote:  
 
 


Hi,
You can enable chat editing using the menu at the top right of the chat screen. This will allow you to edit and delete messages.
The responses cutting off is related to the max tokens in the generation settings. You can increase this, but if you're using Horde it may result in slower response times.
