### ISSUE TITLE
Generation/AI settings broken 

### ISSUE THREAD

**Issue by greasyf** [agnaistic/agnai#297]
The new settings system is poor and inflexible.  Now when using the Cobold with tunnel, the jail does not work and the presets are broken, which greatly interferes with communication in chats.

**Comment by sceuick** [comment]
This'll be fixed very soon.

**Comment by sceuick** [comment]
Third party presets should be fixed now.
The previous generating (service presets, chat adapter, default adapter, etc) were too disparate and confusing. The major change is that AI service is now part of the preset and defined nowhere else (except for legacy users). This is a pretty high-friction change, but is desperately needed to simplify presets.
