### ISSUE TITLE
System error in API recognition, unable to use OpenAI API

### ISSUE THREAD

**Issue by ShEpic** [agnaistic/agnai#299]
All of a sudden I was unable to use the OpenAI API. It writes to me that the quota has been exceeded, although I used it very often during the month. I thought changing the API would help, but I can't save it because I get an error about not matching the KoboldAI API. As I understand it, the menu where we could specify the OpenAI API is recognized by the system as a menu for entering the KoboldAI API. While saving the API, the following error is shown. 

"Failed to update config: Ooba URL provided could not be verified: Invalid URL format. Use a fully qualified URL. E.g.: https://local-tunnel-url-10-20-30-40.loca.lt"

**Comment by malfoyslastname** [comment]
> It writes to me that the quota has been exceeded

1. Check your monthly usage https://platform.openai.com/account/usage
2. 429 errors (quota exceeded) might sometimes be due to other reasons than monthly usage so try also this
try using the playground and check if you receive a similar error and report back please: https://platform.openai.com/playground

If everything seems fine on that front, then try following this video guide, and if it doesn't work, maybe try recording yourself setting up your settings and chat so we have repro steps please:

https://files.catbox.moe/ykv26c.mp4

**Comment by ShEpic** [comment]
The above does not matter, because when choosing any settings, even Horde, it says: ""Failed to update config: Ooba URL provided could not be verified: Invalid URL format. Use a fully qualified URL. E.g.: https://local-tunnel-url-10-20-30-40.loca.lt"

**Comment by ShEpic** [comment]
> > It writes to me that the quota has been exceeded
> 
> 1. Check your monthly usage https://platform.openai.com/account/usage
> 2. 429 errors (quota exceeded) might sometimes be due to other reasons than monthly usage so try also this
>    try using the playground and check if you receive a similar error and report back please: https://platform.openai.com/playground
> 
> If everything seems fine on that front, then try following this video guide, and if it doesn't work, maybe try recording yourself setting up your settings and chat so we have repro steps please:
> 
> https://files.catbox.moe/ykv26c.mp4

The above does not matter, because when choosing any settings, even Horde, it says: ""Failed to update config: Ooba URL provided could not be verified: Invalid URL format. Use a fully qualified URL. E.g.: https://local-tunnel-url-10-20-30-40.loca.lt"
Indeed, I was given a trial (grant) until May 1, which I stubbornly did not notice, and even somehow managed to spend $ 4 out of 18, managed to go into the red. However, this does not explain why I cannot choose any other hosting.

**Comment by sceuick** [comment]
The url format errors have long been resolved. Quota exceeded errors from OpenAI are out of Agnai's control.
