### ISSUE TITLE
Feature: CSS classes to difference between user(s) and character

### ISSUE THREAD

**Issue by notfood** [agnaistic/agnai#30]
A simple feature request: 
I'm writing custom CSS and hit the issue that there is nothing separating the user(s) from the bot in the html markup, css classes would come handy to separate them.

Tangentially, more of a wish than a feature request:
Custom CSS saved onto the character profile, it would allow fancy stuff.

**Comment by sceuick** [comment]
Sure, I can add some do-nothing classes onto the chat messages.
I can't guarantee that the markup and such won't change over time and potentially break your custom css.

If you do come up with some nice alternate chat views, I'd happily consider supporting "chat themes" provided they're not too onerous to implement and maintain. Share a screenshot after you're done if you're comfortable doing so.

**Comment by sceuick** [comment]
Would this suffice?:

![image](https://user-images.githubusercontent.com/60520115/224520254-c47b4405-b6ab-47a8-aba4-ac3c20f6d0a3.png)

**Comment by sceuick** [comment]
> Custom CSS saved onto the character profile, it would allow fancy stuff.

Can you elaborate on this? I'm not sure what exactly you mean. As in which page and which components you'd need identifiable.

**Comment by notfood** [comment]
Yeah, that works. I'd be able to change CSS with 
```css
div[data-sender="bot"] {}
```

> Can you elaborate on this? I'm not sure what exactly you mean. As in which page and which components you'd need identifiable.

Custom CSS per character would allow creators to include CSS to style their bot responses without having to resort to external scripts. The pages that would need to be modified would be character editor, a custom CSS textbox and the character responses, that include something unique to the bot, like a short form of their ID or something small that can be referenced from the CSS. It's more of an idea to develop, not exactly a big part of the feature request here. I'm happy with the data-sender=bot, it does what I need.

**Comment by sceuick** [comment]
Would you require this chat in the message as well?
I can do this by character name as you have more control over that.
`data-bot={char.name}`

**Comment by notfood** [comment]
That'd be ideal

**Comment by sceuick** [comment]
Sure thing, I'll add it in the next release.

**Comment by sceuick** [comment]
Alrighty, being deployed in a50730b.
There will be a `data-bot={bot name}`. It'll be empty if it's a user generated message.
