### ISSUE TITLE
Memory book issue

### ISSUE THREAD

**Issue by ghost** [agnaistic/agnai#302]
Given the points raised about the personality loss, I created a memory book to try to reground the character in its underling mission.
I gave the entry several clear keywords, e.g. mission, purpose.
I then used the ongoing chat options to apply that memory book to the chat, edited the most recent reply to include the keywords and regenerated, but it had no impact on the responses.
I checked the prompt and see that it had also not injected the contents of the memory book there.
Is there specific formatting you have to use on keywords to get them to apply.

**Comment by sceuick** [comment]
This should be resolved for logged in users now in a decent deployment.
