### ISSUE TITLE
Sample chat and real chat not seperated with <START>

### ISSUE THREAD

**Issue by rondlite** [agnaistic/agnai#305]
On a chat, the user continues the last initial chat, there is no <START> tag seperating the sample chat and the user chat, which confuses the bot.
The `hasStart` var is checking for any start tag in the sample chat..

**Comment by malfoyslastname** [comment]
I would consider this a high priority,
Note: <START> should ideally replaced with a System message that says "Start a new conversation" on OpenAI and Claude at least. I think Silly does something along these lines and the presence of <START> in our prompts sometimes causes the bots to also use <START> or other <WORDS>.

**Comment by sceuick** [comment]
This has been by using prompt templates across the board now. The default templates separate the sample chat and history correctly.
