### ISSUE TITLE
Feature request: Use the Tavern card `personality` field

### ISSUE THREAD

**Issue by malfoyslastname** [agnaistic/agnai#307]
This field is called "Summary" in [the ZoltanAI character creator](https://zoltanai.github.io/character-editor/), and "Personality summary" in Silly.

Although it's a summary, I would consider this a **high priority**, as botmakers use this field with the assumption it will be included in the prompt.

Default presets should be amended to contain this field.

**Comment by sceuick** [comment]
I believe both the `description` and `personality` fields from Tavern imports are included. If both are present, they are separated by a line break in the `text` persona attribute.

Is something else required for this?

**Comment by malfoyslastname** [comment]
Oh really? Huh, my bad. Good to close for the time being, but maybe this should be made less ambiguous in the future as others have had this question before.
