### ISSUE TITLE
Improve scroll UX

### ISSUE THREAD

**Issue by malfoyslastname** [agnaistic/agnai#312]
- Chat should scroll to the bottom when a new message is received (especially important for multi-user rooms)
  - might not be the best if backreading a multi-user room and someone posts. must be thought through 
- Non-chat pages should automatically scroll to the top when visited from another page

**Comment by acidbubbles** [comment]
To avoid the issue of scrolling while reading, save the position of the scroll when receiving a message, before updating the html, and only schedule a scroll if the scroll head is at the bottom. I don't think we need anything fancier.

**Comment by sceuick** [comment]
Page should now stick to the bottom.
