### ISSUE TITLE
Change proxy URL box

### ISSUE THREAD

**Issue by ghost** [agnaistic/agnai#316]
Hey there! I have noticed a problem, where AGNAI automatically adds /v1/chat/ after proxy URL, so, if your URL has /v2/ or something else within, it won't work. It can be changed easily in the desktop version, but it would be very useful if we had this in web version as well

**Comment by khanonnie** [comment]
Hi, this situation should be improved as of https://github.com/luminai-companion/agn-ai/pull/315, which is currently merged.

You should now be able to set the third-party API URL as `yoururl.com/v2` and Agnaistic will send your request over to `yoururl.com/v2/chat/completions` (whereas previously it sent it to `yoururl.com/v2/v1/chat/completions`).

Don't set the URL as `/v2/chat`, just `/v2` should work. Agnaistic will still add `/chat/completions` to whatever URL you input.

**Comment by sceuick** [comment]
Re-open if you continue to have any proxy URL issues.
