### ISSUE TITLE
Elevenlabs fails to play custom voice (website, both on laptop and mobile [iOS])

### ISSUE THREAD

**Issue by breastlife** [agnaistic/agnai#317]
Fails to play, gives an error instead. “Error while playing server generated text to speech.” Checked on eleven labs, it successfully generates over there, with the custom voice I picked. (Also correctly skips * and (, so it’s just failing to play it back on the website.)

**Comment by breastlife** [comment]
Tried it on computer as well, it also doesn't work there.

**Comment by sceuick** [comment]
Thanks for the report. This should be fixed now.

**Comment by breastlife** [comment]
Waited for a few minutes on iOS, the error doesn’t pop up anymore, but it also never plays.
