### ISSUE TITLE
No model displayed for The Horde

### ISSUE THREAD

**Issue by CroissantDuNord** [agnaistic/agnai#321]
I cant use any models, the model list is empty, (Note: horde is not down this is working fine on the live version when i tested)
![image](https://github.com/luminai-companion/agn-ai/assets/79372025/8a469695-1cbe-47d0-a1f4-cefdde631028)

I have this reponse in the logs (Even the first time)
![image](https://github.com/luminai-companion/agn-ai/assets/79372025/144ce6e0-806c-4053-87e1-72620d6265cd)

**Comment by CroissantDuNord** [comment]
Edit: This only happed with the docker version, i have no issue when using NPM
Some system information if needed, 
OS: Linux 6.2.12-arch1-1 Docker Version: Docker version 23.0.4, build f480fb1e37

**Comment by sceuick** [comment]
Let me know if this is still an issue.
