### ISSUE TITLE
feat: split oai example messages into "example_user" and "example_assistant" system messages

### ISSUE THREAD

**Issue by malfoyslastname** [agnaistic/agnai#325]
**NEEDS INVESTIGATION**

The OpenAI cookbook suggests you can give example messages using individual system messages and "example_user" and "example_assistant" in the name field.

https://github.com/openai/openai-cookbook/blob/main/examples/How_to_format_inputs_to_ChatGPT_models.ipynb
ctrl-f "example_user", e.g.:

```
        {"role": "system", "name":"example_user", "content": "New synergies will help drive top-line growth."},
        {"role": "system", "name": "example_assistant", "content": "Things working well together will increase revenue."},
        {"role": "system", "name":"example_user", "content": "Let's circle back when we have more bandwidth to touch base on opportunities for increased leverage."},
        {"role": "system", "name": "example_assistant", "content": "Let's talk later when we're less busy about how to do better."},
```

Silly does this.

There's no evidence that doing so yields better results than the current way, again, needs investigation.

**Comment by ewof** [comment]
we had something similar in commit https://github.com/luminai-companion/agn-ai/commit/6af39a66e9657b475794ba7dcda6f98dd184e740
could be modified easily to work with this new method
