### ISSUE TITLE
Adoption of the Character Card V2 spec

### ISSUE THREAD

**Issue by malfoyslastname** [agnaistic/agnai#330]
[The Character Card V2 spec](https://github.com/malfoyslastname/character-card-spec-v2/blob/main/spec_v2.md)

## TODO

- APNG support

# DONE

- Support exporting PNG (can be shipped individually) #344
- Quick and dirty support for V2 fields so the Character List and Chat can be worked on. Should be a new, feature-flagged tsx component that **only exports V2 cards**, and allows importing and storing V2 cards.  #374 
- Support `alternate_greetings` #394
- Support `post_history_instructions` #395 
- Support `character_book`, add a way to open bundled character book inside Memory modal #397l
- Support `system_prompt` #401
- Add preset settings toggle "Ignore character system prompt" and "Ignore character UJB" #401
- Fix how example_dialogue works #403 
  - `<START>` should be transformed to something like `System: New chat started, previous history forgotten`
  - example dialogue should be pruned when context size limit is reached

## Low priority/Extra

- (@malfoyslastname) Polish the V2 Editor UI to be easy to use
- Ensure [the tag UI](https://github.com/luminai-companion/agn-ai/pull/296) is unified with, and works well with V2 cards which will possess tags imported from CharacterHub or other sources
- Devise a UX to make good use of the `character_version` field for characters with the same name?

**Comment by sceuick** [comment]
Done?
