### ISSUE TITLE
About the need for author's note

### ISSUE THREAD

**Issue by BBBBugg** [agnaistic/agnai#335]
Up until now, agnai has been focused on one-on-one chat, so I never felt the need for this feature.
However, using group chat got me thinking about the idea of including support bots in the chat in addition to characters.

This idea is slightly hindered by the fact that all bots in a group chat share the same presets.

The point is that it would be really handy to have one more placeholder that can be created at character creation time so that specific feature prompts can be used in UJB. Like Tavern's author's note.

I realize that the UI can get very messy when this is applied in practice. I apologize for the esoteric post, and for having to use a translator for a not-so-nutritious idea. 

But if this isn't too difficult, I'd really appreciate it if you'd consider it. Thank you.

**Comment by sceuick** [comment]
This may be possible with the upcoming V2 characters spec. They have a `system_prompt` field. When we're adding support for this, support will be added for the `{{system_prompt}} / {{character_prompt}}` field which could be placed in the UJB.
The UJB effectively functions as an author's note and should probably be inserted in the same position for non-gaslight AI services.

Would this solve your need?

**Comment by malfoyslastname** [comment]
note: V2 character cards will also have a `post_history_instructions` field, which is meant to override global UJB setting.

**Comment by BBBBugg** [comment]
I have checked the V2 character cards. I am very happy with it. Thank you!
