### ISSUE TITLE
Error using memory book

### ISSUE THREAD

**Issue by NowAdK** [agnaistic/agnai#340]
I've been experiencing errors since a few days ago. I create and enjoy chatting in the same order every time, but I can't send messages in the new chat room.
I found out that this is an error that occurs when I use a memory book in the chat.
Before using the memory book, the chat bar says 'send a message to OO', but when I use the memory book, it changes to 'send a message' and the chat is not send.
And, error window 'Generation request failed: No character selected to reply with' appears.
How do I solve this?

**Comment by sceuick** [comment]
Thanks for the report. I can reproduce this and I'll release a fix very soon.

**Comment by sceuick** [comment]
I've pushed a fix in #341.
Will be live in a few minutes.
It was introduced when adding multi-bot chat. Some state was lost when a chat was edited (e.g. changing the chat's assigned memory book) which messaging requires.
