### ISSUE TITLE
Chat UI slighly broken in phones.

### ISSUE THREAD

**Issue by DHAn0n** [agnaistic/agnai#342]
It seems like a recent update broke the UI in chats in phones; the chats messages now overlaps with the old ones, covering the lasts lines.

**Comment by sceuick** [comment]
I assume you mean on iOS?

**Comment by DHAn0n** [comment]
Nope; Chrome and Firefox, android 10.

**Comment by sceuick** [comment]
Thanks for the quick report. A fix is being deployed now.
