### ISSUE TITLE
Novel API Error / Failed to generate response 

### ISSUE THREAD

**Issue by Ghostbread** [agnaistic/agnai#345]
I was using the chat for a couple of messages as normal with NovelAI 20BC+ and i didn't change the settings at all so far. I tried to reset the API key by deleting it and putting it back in and trying to export the chat and importing it after but so far all I've tried hasn't worked. This is the Error i get;

![Screenshot_20230517-215307~2](https://github.com/luminai-companion/agn-ai/assets/76554703/3907a82d-f483-4f97-b553-6b0abcf54b23)

It's my first time using this so if anyone has recommendations for settings or AI's i should use for the best experience I'd be thankful.

**Comment by sceuick** [comment]
This error message has been improved. This occurs when you're using a model that your subscription tier doesn't have access to _or_ you're a guest.
