### ISSUE TITLE
Login Issues?

### ISSUE THREAD

**Issue by bluelullaby2** [agnaistic/agnai#350]
Registered an account on the website, attempted to login on another device and keep receiving the following errors at the same time:

Your session has expired. Please login again. 
Authentication Failed. 

Changed password on the device I was logged in at, tried again. Same messages. Logged out of the original device and attempted to login on that device again. Was also unsuccessful. 

Not quite sure what could be going on...?

**Comment by sceuick** [comment]
I'm not aware of any issues. Registration and login seems fine. I'm having no issues logging in across various devices.

**Comment by greasyf** [comment]
> Registered an account on the website, attempted to login on another device and keep receiving the following errors at the same time:
> 
> Your session has expired. Please login again. Authentication Failed.
> 
> Changed password on the device I was logged in at, tried again. Same messages. Logged out of the original device and attempted to login on that device again. Was also unsuccessful.
> 
> Not quite sure what could be going on...?

I'm have this problem too.
