### ISSUE TITLE
TextGen dont work well

### ISSUE THREAD

**Issue by kostya-sec** [agnaistic/agnai#355]
When I selected textgen. I tried webui url and api url and also streaming server url. but all of  them could not response 200.  the response be like 500, 400, and 404. I want to ask for more details for setting TextGen option. thx

**Comment by LukePavelka** [comment]
yep.. me to dont work :(

**Comment by sceuick** [comment]
Heya,
I've deployed some updates to the textgen service. Let me know if they work or not. :crossed_fingers:

**Comment by LukePavelka** [comment]
![image](https://github.com/luminai-companion/agn-ai/assets/76946156/f2fb18a3-8d4d-4809-9b45-7ec84c0d6726)

textgen settings:
![image](https://github.com/luminai-companion/agn-ai/assets/76946156/71350d18-0140-4450-9ff2-eb83c1ab2705)

**Comment by LukePavelka** [comment]
> ![image](https://user-images.githubusercontent.com/76946156/240684818-f2fb18a3-8d4d-4809-9b45-7ec84c0d6726.png)
> 
> textgen settings: ![image](https://user-images.githubusercontent.com/76946156/240685027-71350d18-0140-4450-9ff2-eb83c1ab2705.png)
![image](https://github.com/luminai-companion/agn-ai/assets/76946156/b996256e-bd33-4887-b95c-b715642e629b)

**Comment by sceuick** [comment]
Thanks for trying it. I'll run textgen locally and try to get it all working, but it may be a day or two before I get to it.

I can't recall if Textgen also implemented an Kobold-compatible API? Can you try the Kobold/Third-party service?

**Comment by LukePavelka** [comment]
textgen I use with agn-ai. when I use the kobold API option in agn.ai with the textgen combination, it works fine.

![image](https://github.com/luminai-companion/agn-ai/assets/76946156/a3a2198f-213a-43e7-a82e-05aec015e5a4)

**Comment by ewof** [comment]
#310

**Comment by sceuick** [comment]
These issues should all be resolved.
