### ISSUE TITLE
Frequent message evaporation

### ISSUE THREAD

**Issue by BBBBugg** [agnaistic/agnai#358]
There is an issue where refreshing the page or experiencing a communication error causes all the received responses to disappear. This problem has been occurring frequently due to recent server issues with openAI, causing significant inconvenience. Is it possible to improve this?

**Comment by Rafario448** [comment]
I'm being annoyed by this too. While the 429 error is OpenAI's fault, Agnaistic **deleting the rest of the alternative/swipe messages** when this happens is always annoying. This is something that needs to be fixed.
![image](https://github.com/luminai-companion/agn-ai/assets/6170225/957ca7c7-2f1d-4d27-bfe7-6e2d7db048f6)

**Comment by acidbubbles** [comment]
I was actually going to write an issue but this one is close enough :) I wanted to suggest keeping the waiting message, and instead marking it as error. The toast is usually gone when I switch back to the conversation, so it's unclear there was an error in the first place.

I would also only create the waiting message once the server sends back the generating event.

I'm okay with tackling this one if it's not a priority for you but you approve the refactoring (maybe after the other PRs)

**Comment by sceuick** [comment]
The issue where the swipes are removed when a retry fails should be resolved in aceb520.
Thanks for the report.
