### ISSUE TITLE
"Plain text" is not an option in when creating a chat

### ISSUE THREAD

**Issue by equivalentx** [agnaistic/agnai#36]
When creating character I wanter to use Plain Text persona scheme, but it didn't switch from this persona attribbutes list, so i had to create a character and then edit it, then it switched.

Anyway, when I tried to create a new chat with this character there was no Plain Text option at all, just other 3, and my plain text from earlier was inserted as attribute "text"

And my plain text is just "character_name from anime_name", it worked well with openai with tavernai, it just took all the info about the character from it's database or whatever, but what about this agnai?

**Comment by sceuick** [comment]
Thanks for reaching out.

I think "plain text" persona type was overlooked in the create chat screen. Will fix. :smiley:

**Comment by sceuick** [comment]
Hopefully fixed by 3997c12

**Comment by equivalentx** [comment]
> Hopefully fixed by [3997c12](https://github.com/luminai-companion/agn-ai/commit/3997c120abe899ac776f213f99aacc0d12da979b)

![image](https://user-images.githubusercontent.com/127750474/224738884-78c3da89-7529-4cbf-b1a0-ab041227f792.png)

**Comment by equivalentx** [comment]
Also direct speech and actions are the same color even tho i use markdown ie asterisks, which is inconvenient

**Comment by equivalentx** [comment]
Also plain text cuts off at 75 characters

**Comment by equivalentx** [comment]
Also plain text cuts off at 75 characters

**Comment by sceuick** [comment]
Where does plain text cut off at 75 characters?
Do you mean the field doesn't allow more than 75 characters?

**Comment by sceuick** [comment]
The dropdown should be fixed with 3ccf504 now.
It'll be disabled if the characters persona kind of plain text and will only display "Plain text".

**Comment by equivalentx** [comment]
> Where does plain text cut off at 75 characters? Do you mean the field doesn't allow more than 75 characters?

when editing the character and clicking update

**Comment by sceuick** [comment]
Okay, I think I've gotten to the bottom of this now! It turned out to be related to splitting based on `,` commas which is how regular attributes are handled.
Hopefully fixed by aa2f9d1.

**Comment by sceuick** [comment]
Pretty sure this is all solved now.
