### ISSUE TITLE
Bug: All chats disappear after refreshing, requiring re-login

### ISSUE THREAD

**Issue by ghost** [agnaistic/agnai#370]
When refreshing the 'Chats' page, all chats disappear. Refreshing again causes all chats to flash in before disappearing again. Logging out and back in fixes this, but happens again when refreshing 'Chats' page.

https://github.com/agnaistic/agnai/assets/130247549/202488d1-e67e-45a4-b8d0-027ff1d9f743

**Comment by sceuick** [comment]
Is this with a particular browser?
Are you using the live version or self-hosting?

**Comment by sceuick** [comment]
Okay, I believe this is fixed now. Thanks for the report.
