### ISSUE TITLE
I keep getting logged out

### ISSUE THREAD

**Issue by cherikorazz** [agnaistic/agnai#372]
Whenever i send a single message i get logged out and have to re log in

**Comment by sceuick** [comment]
I'll need a bit more info to work on.
Are you using the live version? Which AI service?

**Comment by cherikorazz** [comment]
to be honest, all i really know is that when i refresh the page, or try to regenerate a new response, i get a notification thing saying “cannot generate response, chat doesn’t exist” then a few seconds after ill be kicked back into the login page

**Comment by cherikorazz** [comment]
![IMG_3406](https://github.com/agnaistic/agnai/assets/134824618/cac9fcf8-3509-49eb-b28a-a290c01f9a9d)

**Comment by sceuick** [comment]
To get around this quickly I'd recommend registering.
If your browser doesn't support local storage then guest access will not work at all.

**Comment by cherikorazz** [comment]
> To get around this quickly I'd recommend registering.
> If your browser doesn't support local storage then guest access will not work at all.

i am registered though

**Comment by sceuick** [comment]
Make sure you're signed in. That particular error only occurs for guest users.

**Comment by cherikorazz** [comment]
So, i’ve been signed in for a while; but it still logs me out of my account after every message i send, and now the bots aren’t even sending messages back

**Comment by sceuick** [comment]
I've removed a "session expired" event when the server returned a bad response.
Hopefully we all get logged out far less frequently now.
