### ISSUE TITLE
Bug in Kobold proxy logging 

### ISSUE THREAD

**Issue by greasyf** [agnaistic/agnai#373]
The password in the Kobold tab is not saved and disappears every time you switch to another tab.  Android system. Google Chrome browser.

**Comment by sceuick** [comment]
Passwords and keys are typically "omitted" from the UI after they are saved.
Are you a guest or registered?

**Comment by greasyf** [comment]
I was registered, but now I've been kicked out of the login and I can't log into the account with my login and password.

**Comment by greasyf** [comment]
Was the account banned or is it possible to restore it?
