### ISSUE TITLE
Bots won't load chats at all, also some other issues. 

### ISSUE THREAD

**Issue by chroniclnsomnia** [agnaistic/agnai#375]
Everytime i enter something in, it either doesn't load, which is the most common outcome, or it just spouts random words with no correlation with each other. I am using Horde with the default pygmalion or whatever its called. I used novel ai, and used up all my  (ink?) And trying to turn back to horde, it just won't work. I can't download characters either, as hitting create just sends it into an infinite load. ALso the fact that when the chat DOES load, it either says complete gibberish, or something the completely veers off the course of the topic i'm going to.

**Comment by chroniclnsomnia** [comment]
Ok, so now their loading for sure, but not saying anything related to the chat i was having for 4-5 messages prior, when everything was going fine.

**Comment by sceuick** [comment]
If you're using Horde your responses may vary.
Have you selected a specific model or are you using "Any" horde model?

**Comment by chroniclnsomnia** [comment]
> If you're using Horde your responses may vary. Have you selected a specific model or are you using "Any" horde model?

I'm using the pygmalion 6b, and after a few messages they just go insane. one second i'm doing this rpg, and the next i'm using a metal chair against a random tavernskeep?

**Comment by chroniclnsomnia** [comment]
Also the fact the it interrupts itself, no matter how high i put the context limit.
