### ISSUE TITLE
Can only use Horde

### ISSUE THREAD

**Issue by DetectiveHeavy** [agnaistic/agnai#376]
Yesterday it worked fine. I could choose any bot / ai i wanted. Now it only allows horde. I tried it with different characters which worked yesterday but i still can only choose horde. Am i missing something?

![bug](https://github.com/agnaistic/agnai/assets/88740752/d962e809-d211-4acf-90f8-d09871c102be)

**Comment by sceuick** [comment]
Thanks for raising. I'll deploy a fix for this in a moment. I accidentally enabled the wrong flag for this particular modal after cleaning up some of the preset code.

**Comment by sceuick** [comment]
Should fixed now :+1:
