### ISSUE TITLE
NovelAI repetition 

### ISSUE THREAD

**Issue by puffycloude** [agnaistic/agnai#377]
When using NovelAI’s Clio, i’ve found that getting pretty deep into a conversation makes the bot start to repeat itself or use long illegible run on sentences. I think this is an Agnai thing because it hasn’t happened on the actual NovelAI website

**Comment by sceuick** [comment]
Do you know which preset you use when you're using the NovelAI editor?

**Comment by puffycloude** [comment]
> Do you know which preset you use when you're using the NovelAI editor?

I usually default to Clio - Talker C

**Comment by sceuick** [comment]
NovelAI recently deployed a fix for this. I've also deployed some minor fixes for the Clio preset as well.
Hopefully this is resolved :crossed_fingers:
