### ISSUE TITLE
[Feature Request] Allow token streaming from Kobold(cpp)

### ISSUE THREAD

**Issue by SammCheese** [agnaistic/agnai#379]
Some models might take a while to generate on some hardware.
So to not always have 3 dots hovering around for half an hour, it might be beneficial to implement token streaming similar to Kobold lite's implementation. It would severely reduce idle waiting times for the user and benefit the user experience.

**Comment by sceuick** [comment]
Need to wait for Kobold to implement an API that supports it. I'll likely need to be notified when that happens.
Happy to implement when an server-side events API is available in Kobold.

**Comment by Thangzy** [comment]
Hey !

Just wanted to let you know that @SammCheese added a compatible endpoint for agnaistic in their latest version 
https://github.com/LostRuins/koboldcpp/releases/tag/v1.30.3

Thank you for your work !

EDIT: credits is important kids

**Comment by SammCheese** [comment]
That was me xd

**Comment by Thangzy** [comment]
Oh my bad ahah, thank you for doing it !

**Comment by SammCheese** [comment]
Implemented in 0fd4b58
