### ISSUE TITLE
Prompt preview malfunctions

### ISSUE THREAD

**Issue by BBBBugg** [agnaistic/agnai#382]
When I run the prompt preview now, I get an error that only includes the gaslight prompt, not the chatlog.

**Comment by sceuick** [comment]
Thanks for raising the issue. I'll fix it _promptly_.

**Comment by sceuick** [comment]
I'm trying to reproduce this particular issue. When I use the prompt preview (the modal) it shows the chat log for me with gaslight and non-gaslight presets.
Can you give me a description of your specific config to help reproduce the issue?
- Which AI Service
- Gaslight enabled or not
- What the gaslight is (or resembles, the {{placeholders}} are important

**Comment by sceuick** [comment]
Okay, I believe I've gotten to the bottom of this. A fix is being deployed at the moment.
