### ISSUE TITLE
Bug: Horde model won't update?

### ISSUE THREAD

**Issue by Cheesestrings2929** [agnaistic/agnai#384]
I keep trying to select a Model, but whenever I save and open a chat or just reload, it doesn't stay saved, so it makes chatting practically impossible. I don't know how to fix it

**Comment by sceuick** [comment]
I believe this is a UI bug. The models you've selected should be saved, but not reflected in the UI. I'll fix.

**Comment by sceuick** [comment]
This should be fixed now.
