### ISSUE TITLE
Issue: Messages not being sent 

### ISSUE THREAD

**Issue by Ausagipop** [agnaistic/agnai#386]
So, I’ve tried using.. Horde, Novelai, and Openai, But no matter what, the bots response will buffer for like.. 20 minutes, and will never send, then after a LONG wait i get an error message saying like.. “Permission not granted” or “Message not available” or something else like that. Its been doing this for two days now 🥲
![IMG_3445](https://github.com/agnaistic/agnai/assets/135183890/76140410-8e72-46ca-94ec-a15ceba2cabd)

**Comment by sceuick** [comment]
Double check that you've selected a NovelAI or OpenAI preset in the Chat Generation Settings (top right menu in the chat screen, the three dots in your screenshot). OpenAI and NovelAI usually respond very quickly (in seconds).
I'll try to show which service is in use on mobile as this is a pretty common issue.

**Comment by Ausagipop** [comment]
I’ve made sure each time, the issue i’m experiencing is just that the bots WILL NOT send the reply, the current loading response has been buffering for an hour now, i think the last message i properly received was yesterday morning

**Comment by sceuick** [comment]
The messages have a timeout of 2-3 minutes max. If you're registered you can safely refresh and you won't lose your message if it has been generated.
"Message not available" is typically an error to only occurs when using Horde. If you haven't already, head to aihorde.net and create an API key.
 NovelAI and OpenAI require keys as well.

**Comment by SammCheese** [comment]
I believe this has been fixed in [5320acf](https://github.com/agnaistic/agnai/commit/5320acff7412b1b5771d1ad9e1298b30b5965539), no?

**Comment by sceuick** [comment]
Hoping this is resolved now.
