### ISSUE TITLE
Bug: Text cutting itself off despite "Max new tokens" Being higher than 2000

### ISSUE THREAD

**Issue by chroniclnsomnia** [agnaistic/agnai#400]
I have seen this with every chat bot I have used. I am on Opera GX, and I am currently using Horde. My model is chronos-13b-4bit. Every time I type, no matter what my chat generation settings are, the chat bots cut themselves off at exactly 60 words. I have even placed the "max new tokens" setting to the max, and have seen no difference. If they have no words, and are just a string of one letter, It will cut off at the end of line 3 or the beginning of line 4. I will provide additional info if needed.

Example: Robot tilts its head slightly, considering {{User}}'s situation. That's certainly an interesting issue. Have you tried adjusting the Max Content Length setting in your Generation Settings? This may help increase the amount of text the chat bots can use in their responses. Additionally, have you checked for any updates or recent changes made to the Agn AI platform? These may

At the end you can see the random snipping.

Edit: It seems that after looking at it, My tokens are set to a limit of 71, despite me having my settings to much higher than that.

**Comment by sceuick** [comment]
This isn't going to be a bug with Agnai. There's nothing that can really be done on my side to improve this. Max tokens is sent as-is to the service and Agnai retains the enter contents of the message _except_ when it tries to speak on behalf of another character.
