### ISSUE TITLE
Character Impersonation

### ISSUE THREAD

**Issue by puffycloude** [agnaistic/agnai#402]
When impersonating a character, using the {{user}} placeholder in the greeting still defaults to the display name rather than the name of the character youre impersonating. Hope I explained that coherently.

**Comment by sceuick** [comment]
Do you mean in the "prompt preview" modal?

**Comment by sceuick** [comment]
I understand the issue now. I will attempt to rectify soon.
This currently only affects the frontend. The prompt sent to the AI is correct.

**Comment by sceuick** [comment]
Should be fixed now.
