### ISSUE TITLE
Sometimes double {{char}} input is entered in the prompt.

### ISSUE THREAD

**Issue by BBBBugg** [agnaistic/agnai#408]
Due to frequent occurrence of {{char}}: being repeated twice in the prompt, there is a bug where {{char}}: is always appended in the subsequent response. Although I'm not sure about the conditions, this bug doesn't occur every time, but once it happens, it persists until the chat conditions change.

At first I thought it was a case of openAI mislearning, but then I realized that there was a problem with the prompting process.

**Comment by sceuick** [comment]
This should be resolved now. Response parsing was adjusted to remove these instances.
