### ISSUE TITLE
Kobold & 3rd Party config in Preset instead of AI settings

### ISSUE THREAD

**Issue by BlipRanger** [agnaistic/agnai#409]
I do a lot of testing between a local Kobold instance and a 3rd party instance (also Kobold, truncates sentences, etc.) and wanted to know if it might be possible to separate the Kobold and 3rd party AI settings tabs so that we could have both. Thanks.

**Comment by sceuick** [comment]
The "third party format" and "third party url" need to be in the preset, rather than in the settings.
I'll edit this issue as an "enhancement".

**Comment by sceuick** [comment]
I've added these two properties to the presets, but not the password.

**Comment by sceuick** [comment]
This has been implemented.
