### ISSUE TITLE
Main character duplicated in chat

### ISSUE THREAD

**Issue by severedisrepair** [agnaistic/agnai#410]
Sometimes, the character is registered twice among participants in the chat, with no way of deleting the duplicate, since it's also flagged as the main character.  I haven't noticed this issue before today, so I think it's fairly new.

**Comment by sceuick** [comment]
That was probably in the most recent deployment. Thank you, will fix.

**Comment by sceuick** [comment]
Should be fixed in the chat page and in the members modal.
Will fix in the chat list next.
