### ISSUE TITLE
(Bug Fix) Refreshing back to old messages

### ISSUE THREAD

**Issue by ashton-jiffy** [agnaistic/agnai#421]
This bug often happens if you returned to the chat page of your character after leaving it for a long time.
It refreshes back to the old message, and it would refresh back to the new one if you refresh the page several times

https://github.com/agnaistic/agnai/assets/67291514/35f0bfc3-c521-4377-a04f-3a8ebda7093e

**Comment by sceuick** [comment]
What device + browser is this?

**Comment by ashton-jiffy** [comment]
> What device + browser is this?

Safari and IPAD (9th generation)

**Comment by ashton-jiffy** [comment]
Keeps happening as of now

**Comment by sceuick** [comment]
How about now? Re-open if it's still an issue.
