### ISSUE TITLE
Can't scroll when starting a new conversation

### ISSUE THREAD

**Issue by severedisrepair** [agnaistic/agnai#424]
On Brave, I can't scroll down when trying to start a new conversation. I think it's related to the new UI. I tried using Firefox, and it worked just fine there, though the UI looks like it did last week. The same happens when trying to edit chat. A similar issue occurred in the beginning of May (Issue #283 ).

**Comment by sceuick** [comment]
This is working fine for me on Brave desktop and Android. Is it on a mobile device?

**Comment by severedisrepair** [comment]
No, on desktop. I don't know if it's fixed now, since there's another issue where Agnaistic seems to fail to load at all. It says it can't get settings from the server.

Update: The site loads, but I still can't scroll on the parts where something like the edit chat overlays the page.

![Screenshot (6)](https://github.com/agnaistic/agnai/assets/124266563/f9317800-ee0f-447f-8434-fd40b27e6d55)

**Comment by severedisrepair** [comment]
Update the 2nd: I un- and re-installed the browser, and things seem to work.

**Comment by Alb3rT00r** [comment]
Im having the same issue on Android Chrome, not only it doesn't let me create a new chat because the new chat message is cropped, but in the chat itself almost all windows are useless because it doesn't let me to scroll down.

**Comment by sceuick** [comment]
I believe this was due to a bad cache. If you haven't already, clear your browser cache and it should all be good.
Chrome should definitely be completely fine.
