### ISSUE TITLE
Chat doesn't show new lines

### ISSUE THREAD

**Issue by teasouse** [agnaistic/agnai#43]
Good Morning sir. Can you fix this please? And maybe make italic text a bit darker for good readability?
![image](https://user-images.githubusercontent.com/10737240/225445898-0f99c2a2-b614-4958-b3e0-4fc09dd9e603.png)
![image](https://user-images.githubusercontent.com/10737240/225445934-4804b017-950e-44d8-aefb-623ddad86e13.png)

**Comment by sceuick** [comment]
I've hopefully fixed this with 431f270b89505c58a49d5d581cbba2246f992bac

**Comment by sceuick** [comment]
Re-open if it isn't fixed.

**Comment by teasouse** [comment]
I can see my newlines in chat now, but AI seem to ignore it in the conversation samples I gave and still writes without newlines.
