### ISSUE TITLE
No access to various parts of the site

### ISSUE THREAD

**Issue by ShEpic** [agnaistic/agnai#430]
An error is written about the impossibility of loading sections of the site, like "Could not get settings from server"

**Comment by sceuick** [comment]
I'm hoping this is fixed now. Please let me know if you're still having issues!

**Comment by ShEpic** [comment]
It's still happen if you select the "character" tab and then from it, trying to use different parts of the site. Error on character's page called "failed to retrieve characters"

**Comment by ShEpic** [comment]
> I'm hoping this is fixed now. Please let me know if you're still having issues!

"Agnaistic failed to load" error if trying to refresh. And please look at my comment before that, I forgot to quote you.

**Comment by ShEpic** [comment]
P.S. Site is broken, please return it to the state what was in the start of last week, and new changes please test somewhere else on the beta. The last stable update was adding multi-chat.

**Comment by sceuick** [comment]
It seems that clearing the browser cache clears up the issue. You can test another browser as well which would accomplish the same thing. This might be the result of a bad cache which is why only a small number of users are affected.

When this was first reported I was re-configuring the CDN and how the front-end is served.

**Comment by ShEpic** [comment]
> It seems that clearing the browser cache clears up the issue. You can test another browser as well which would accomplish the same thing. This might be the result of a bad cache which is why only a small number of users are affected.
> 
> When this was first reported I was re-configuring the CDN and how the front-end is served.

Worked. 👍
