### ISSUE TITLE
[Feature Request] Author's note

### ISSUE THREAD

**Issue by nothingsuspiciousright** [agnaistic/agnai#440]
Hello!! 
I was wondering if it is possible for you to add the Author's note possibility to Agnai? It is extremely useful when JB has too much influence on the response, while the Author's Note we can put in the chat at a depth of 1+ message, which allows the AI to still follow the instruction, but not go crazy on it.

**Comment by sceuick** [comment]
I won't be adding `Author's note`, but instead something more generic.
Prompt templates will eventually support insertion at arbitrary points in the chat history using something that will resemble:

```
{{#each history}}
{{line 4}}({{char}} is an alien){{/line}}
{{/each}}
```
