### ISSUE TITLE
Feature Request: Leaving / deleting multi-user chats

### ISSUE THREAD

**Issue by ghost** [agnaistic/agnai#441]
![image](https://github.com/agnaistic/agnai/assets/130247549/faedc829-40ec-491f-91db-2202cda03246)
I get the error 'Failed to delete char: Forbidden' when I try to delete a multi-user chat from the past. It's annoying to have them permanently sitting there. It would be nice to "delete" or hide them even if you didn't start the chat.

**Comment by sceuick** [comment]
Yup, I'll fix this one today.

**Comment by sceuick** [comment]
Deployed a fix for this. Let me know if it's still an issue.

**Comment by ghost** [comment]
@sceuick 
![image](https://github.com/agnaistic/agnai/assets/130247549/7eab6e81-c83e-427a-b972-3b8fd6063663)
~Same thing as before.~
Nevermind! Error appears but when I refreshed, the chats were gone. Thank you.

**Comment by sceuick** [comment]
Just found the issue that raises the error, but still removes the chat.
