### ISSUE TITLE
Bug: Strange unnecessary spacing of memory book keywords

### ISSUE THREAD

**Issue by ghost** [agnaistic/agnai#443]
https://github.com/agnaistic/agnai/assets/130247549/37ef4e31-883f-414a-9fa5-1558b52d396b

When putting keywords into entries and clicking off, spacing is automatically added every time no matter what, even if you already have spacing. This means that each time you add a keyword, more spaces are applied to it which add up.

EDIT: After some more testing, it appears that this also prevents keywords from working if they have more than one space after the comma.

**Comment by sceuick** [comment]
I believe this is fixed now.
