### ISSUE TITLE
The "agnai" command no longer launches agnai after an update

### ISSUE THREAD

**Issue by ArakiSatoshi** [agnaistic/agnai#445]
I'm on Windows 10, npm@9.7.1. I had agnai installed with the Quick Start method:

```
npm install agnai -g
agnai
```

I used to update it by simply running `npm install agnai -g`, and it worked well. Two days ago, I did the same, but now calling `agnai` in the command line returns only one thing:

`agnai is not recognized as an internal or external command, operable program or batch file.`

I tried doing `npm link agnai`, then `npm uninstall agnai -g` and `npm install agnai -g` again, but none of these helped.

`npm list -g` only returns this:

```
+-- agnai.7z@
+-- agnai@1.0.21
`-- npm@9.7.1
```

How would I fix this issue without getting into the manual installation? Excuse me if some steps were irrelevant or some missing, I just know almost nothing about npm.

**Comment by sceuick** [comment]
This is fixed now from 1.0.22 onwards.
Sorry about that.
