### ISSUE TITLE
Option to make italic text a bit different color

### ISSUE THREAD

**Issue by teasouse** [agnaistic/agnai#45]
Maybe a bit darker like in Tavern?

**Comment by sceuick** [comment]
Sure, this shouldn't be any trouble. I forgot this when I was fixing the line breaks.

**Comment by sceuick** [comment]
I'm slightly adjusted the emphasis colour. When I loop back around to UI improvements I'll be sure to allow users to customise font colours of various parts of the chat (bot name, character name, chat emphasis colour, chat normal colour).
I'll add an item into the roadmap for this.
