### ISSUE TITLE
Markdown in chat window does not retain the raw data

### ISSUE THREAD

**Issue by sandwichdoge** [agnaistic/agnai#450]
Symbols in the markdown in the chat output shouldn't be changed/reformatted.
Please see the attached picture.

![agnaimarkdown](https://github.com/agnaistic/agnai/assets/38368906/ef9b7d1e-2b81-472c-aa28-d2ff9797a23d)
The lt and gt symbols are converted into weird marks. It's unusable when I want to copy some code from the output. Here's what's in my clipboard when I copy the markdown.
```
2 › 1
1 ‹ 2
```

**Comment by sceuick** [comment]
I'll need to add an option to disable this. It's very deliberate to avoid script tags.

**Comment by sceuick** [comment]
The `lt` and `gt` symbols have been replaced with HTML entities now that should _hopefully_ render correctly.

**Comment by sandwichdoge** [comment]
Hmm this is what I get now.
![image](https://github.com/agnaistic/agnai/assets/38368906/e6279cfa-ae00-4b24-953c-babe53ff1c74)
Is it intended? What do you mean by avoiding script tags btw, if you don't mind me asking?

**Comment by sceuick** [comment]
For security reasons.

**Comment by sandwichdoge** [comment]
Fair enough, but if it's impossible to make markdown secure then you should probably revert to using the alternative symbols like before, because the guys who use greentext prompts probably won't like this new change.

**Comment by sceuick** [comment]
Yeah, I'll need to tweak for code blocks. I'll sort it out shortly.

**Comment by sceuick** [comment]
This should all be fixed now.
