### ISSUE TITLE
Sending message to character results in error

### ISSUE THREAD

**Issue by shakealeg** [agnaistic/agnai#453]
I am running Agnaistic manually with git clone and npm. I am running these on Windows 11.
I am using KoboldAI locally with pygmalion-13b.
The error I get is:
```
(Send) Generation request failed: request entity too large
```
In the console, it appears to be trying to connect to Horde for some reason.
If you know of a solution, please let me know.
Thanks.

**Comment by sceuick** [comment]
Request entity too large is due to the payload being sent to server is large exceeds the limit.
Can you provide some info on how you're using agnai?
1. Live site or locally hosted
2. Registered or guest

**Comment by sceuick** [comment]
If you're running locally you can increase the `IMAGE_SIZE_LIMIT` and `JSON_SIZE_LIMIT` variables.
