### ISSUE TITLE
Feature Request: Claude streaming

### ISSUE THREAD

**Issue by ghost** [agnaistic/agnai#455]
It would be nice to be able to enable streaming for Claude presets similar to OpenAI presets. The Anthropic Typescript API Library was recently updated, and it has a section on streaming and an example file.

https://github.com/anthropics/anthropic-sdk-typescript

**Comment by khanonnie** [comment]
On this topic, Anthropic has recently introduced a second version of their API with a completely new (and not backwards compatible) implementation for their SSE streaming format. You currently have to opt into the new version but presumably they will make it the default soon and retire the old one. https://docs.anthropic.com/claude/reference/versioning

I will probably take a stab at this this weekend, unless someone is already working on this -- but if anyone _is_ already working on this, they should probably implement it against the new API version and not the to-be-deprecated old one.
