### ISSUE TITLE
Feature Request: Chat Scenario

### ISSUE THREAD

**Issue by ashton-jiffy** [agnaistic/agnai#463]
When making a chat, you need to pick a scenario of what the chat would be like.

Concept: 
![concept](https://github.com/agnaistic/agnai/assets/67291514/df607399-869f-4fe4-adc0-e47f4be9a37a)

**Comment by sceuick** [comment]
This is already possible by enabling "overrides" when you create the chat.

**Comment by ashton-jiffy** [comment]
Ok
