### ISSUE TITLE
Editing characters too slowly eats edits

### ISSUE THREAD

**Issue by mtaanquist** [agnaistic/agnai#466]
**Describe the bug**
When editing a character, if you take too long to hit the "Update" button, your edits will be reverted to what's stored in the database.

**To Reproduce**
1. Go to any character
2. Click on the Edit button
3. Start writing in any of the fields
4. Leave the page be for a moment
5. Observe that your changes disappear after a little while

**Expected behavior**
The edits should stay until you navigate away (discarding your changes) without updating.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 11
 - Browser: Microsoft Edge 
 - Version: Version 114.0.1823.58 (Official build) (64-bit)

**Additional context**
It appears to happen whenever the client "phones home", and coincides with one of these console messages:

```console
{"type":"connected","uid":"b98207c7-a823-48b7-acc2-12da8a62ed3b"} socket.ts:67 
{"type":"connected","uid":"edb310e0-c93f-478a-a8e8-daadba71fadb"} socket.ts:67 
{"type":"connected","uid":"749687ad-b160-454c-a45d-2777e03d952d"} socket.ts:67 
{"type":"connected","uid":"ca50fdea-8ac1-4ea4-8b77-795d3d14837b"} socket.ts:67 
{"type":"connected","uid":"2bc2651e-a116-48b7-a781-9405cb048597"} socket.ts:67 
{"type":"connected","uid":"052eb1af-db33-4206-a25b-41c2bacea34f"} socket.ts:67 
{"type":"connected","uid":"608f9189-2093-4a01-8f23-3535abe5df1a"} socket.ts:67 
```

My server is hosted on Ubuntu 22.04 LTS, running from the main branch, and proxyed behind nginx. This is my nginx config file, with the domain redacted:

```nginx
server {
        client_max_body_size 200M;

        server_name chat.domain.tld;

        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_pass http://localhost:3001;
        }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/chat.domain.tld/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/chat.domain.tld/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
```

Let me know if there's any other information you'd like. 

Thanks for a great application!

**Comment by sceuick** [comment]
Ah, I believe the websocket re-connecting causes another `/init` request which causes various parts of the user's state to get updated.
Thanks for finding the cause.

**Comment by sceuick** [comment]
Please re-open if you continue to experience this on the latest version.
I've refactored the character editor to reload less-often on state changes.

However your websocket shouldn't be reconnecting this often. Websocket disconnects should only occur when the Node.js webserver shuts down or restarts.
