### ISSUE TITLE
POST request to /api/user/ui fails with 404 when logged in

### ISSUE THREAD

**Issue by mtaanquist** [agnaistic/agnai#468]
**Describe the bug**
While logged in and idling in the client, the client periodically calls a request which fails. I am unsure if this has any actual effect, but it does spam the console log.

**To Reproduce**
1. Log in
2. Monitor the console log

This is what happens in the Network log:
```
GET wss://chat.domain.tld/ HTTP/1.1 -- 200 OK
GET https://chat.domain.tld/api/user/init? -- 200 OK
POST https://chat.domain.tld/api/user/ui -- 404 Not Found
```

The POST-request has the following payload:
```json
{"theme":"sky","themeBg":"truegray","bgCustom":"","bgCustomGradient":"","mode":"dark","avatarSize":"md","avatarCorners":"circle","font":"default","msgOpacity":0.8,"msgBackground":"--bg-800","botBackground":"--bg-800","chatTextColor":"--text-800","chatEmphasisColor":"--text-600","chatWidth":"full","logPromptsToBrowserConsole":false,"imageWrap":false,"light":{"msgBackground":"--bg-800","botBackground":"--bg-800","chatTextColor":"--text-800","chatEmphasisColor":"--text-600"},"dark":{"msgBackground":"--bg-800","botBackground":"--bg-800","chatTextColor":"--text-800","chatEmphasisColor":"--text-600"}}
```

The console logs this as being an error in `api.ts:92`.

**Expected behavior**
It shouldn't fail in sending the POST request.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 11
 - Browser: Microsoft Edge 
 - Version: Version 114.0.1823.58 (Official build) (64-bit)

**Additional context**
It appears to happen whenever the client "phones home", and logs this console message.

Call stack:
```console
POST https://chat.domain.tld/api/user/ui 404 (Not Found)
callApi @ api.ts:92
post @ api.ts:54
updateUI @ user.ts:156
updateUI @ user.ts:177
wrapped.<computed> @ create.ts:102
(anonymous) @ user.ts:53
emit @ events.js:158
init @ settings.ts:79
wrapped.<computed> @ create.ts:119
await in wrapped.<computed> (async)
(anonymous) @ settings.ts:167
onMessage @ socket.ts:77
```

My server is hosted on Ubuntu 22.04 LTS, running from the main branch, and proxyed behind nginx. This is my nginx config file, with the domain redacted:

```nginx
server {
        client_max_body_size 200M;

        server_name chat.domain.tld;

        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_pass http://localhost:3001;
        }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/chat.domain.tld/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/chat.domain.tld/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
```

Let me know if there's any other information you'd like.

**Comment by mtaanquist** [comment]
I'm unsure if this is related, but every now and then, I see this in my console as well:

```console
runtime-22f18695244dbe84.js:84 

WebSocket connection to 'wss://chat.domain.tld:1234/' failed: 
6sb9v	@	runtime-22f18695244dbe84.js:84
newRequire	@	index.fdd53e66.js:71
(anonymous)	@	index.fdd53e66.js:122
(anonymous)	@	index.fdd53e66.js:145
```

**Comment by sceuick** [comment]
The `/api/user/ui` route should definitely exist now.

As for your websocket errors, I think you're reverse proxying to the wrong port. You'll want to reverse proxy to `3001` instead of `1234`. The websocket connection to `1234` is being created by the parcel bundler dev server for hot-reloading. This means you're reverse proxying to the dev server instead of directly to the express server.

> I'm unsure if this is related, but every now and then, I see this in my console as well:
> 
> ```
> runtime-22f18695244dbe84.js:84 
> 
> WebSocket connection to 'wss://chat.domain.tld:1234/' failed: 
> 6sb9v	@	runtime-22f18695244dbe84.js:84
> newRequire	@	index.fdd53e66.js:71
> (anonymous)	@	index.fdd53e66.js:122
> (anonymous)	@	index.fdd53e66.js:145
> ```
