### ISSUE TITLE
(Send) Generation request failed: Cannot read properties of undefined (reading 'find')

### ISSUE THREAD

**Issue by ArakiSatoshi** [agnaistic/agnai#477]
agnai's version is 1.0.70 (installed/updated with `npm install agnai -g`).

My setup is a Kobold / Third-Party URL (a reverse proxy) with the preset set as "Kobold / 3rd Party" in the AI service, OpenAI Model set as Turbo. But when I send any message to a bot, the system gives me the following error:
`(Send) Generation request failed: Cannot read properties of undefined (reading 'find')`

I had a similar problem yesterday and was unable to use agnai as well, though instead of the error as it shows today, it was showing the loading circle endlessly, with my message still staying in the text input field as not sent. The terminal running agnai with the `-d` parameter wasn't showing the message being sent to the reverse proxy as it usually does.

It was working normally before with the same setup, somewhere in version 1.0.40 or so, can't recall precisely. What might be the issue?

**Comment by sceuick** [comment]
This should hopefully be fixed in the latest version.
