### ISSUE TITLE
"Horde request failed: Bad Request. Input payload validation failed" (error when send message)

### ISSUE THREAD

**Issue by ShEpic** [agnaistic/agnai#482]
This error appears immediately after trying to send a message to a character. It showed up just yesterday. I did not change the settings, horde api is registered, workers exist and access to them is not limited.
![err](https://github.com/agnaistic/agnai/assets/54413798/efd91685-d57b-47c4-b539-87f11813d273)

**Comment by sceuick** [comment]
I'll push a fix for this shortly. It'll provide more detail, but I'll also triage the issue behind the scenes that is causing bad payloads.

**Comment by sceuick** [comment]
These changes are live now. Let me know if you have any further issues.
