### ISSUE TITLE
Feature request: Text RPG style RP (like AID) 

### ISSUE THREAD

**Issue by ShEpic** [agnaistic/agnai#488]
The chat is good, but even with multichat it is difficult to make a full-fledged RP.
Need to be inspired by AI Dungeon and Novel AI or Kobold AI to create a field for creating RP in text RPG mode. 

In my understanding, this is a test line for entering text, at the top is an output field. On the right are RPG elements such as HP, mana, stamina, weight, money, and on the left is a constantly changing field that contains the names of the mentioned characters from the output field without avatars, when clicked, you can interact via chat, and the names appear or disappear depending on the plot , and the names can be acted upon as keywords.

For each name, a separate prompt is automatically made, depending on the name and fame of the mentioned character and the context. With just a name and story context, it's possible to chat with a character within a text-based RPG, making the chat separate but not detached from the story so the AI doesn't mix it all up. The context will actualize the character's life in a particular story, just like it is in multichat chat, and his name gives him a personality, just like when creating a character in the 
usual way.

At the same time, the neural network should not play the role of the character of the account owner, and let him (owner) play the character (or himself) in first person.

![example](https://github.com/agnaistic/agnai/assets/54413798/2630a27c-e812-46ec-a97b-6ed87e167a99)

**Comment by sceuick** [comment]
An RPG mode should be possible with the addition of JSON schemas. It just needs to be rolled out to more services that support it JSON formatted/constrained responses. `Tabby` and `Llama.Cpp` third party presets currently support it. I believe There are quite a few more that do as well.
