### ISSUE TITLE
How can i set a default user config to use predefine 3rd party API?

### ISSUE THREAD

**Issue by xiaol** [agnaistic/agnai#498]
"Please ask questions on Discord! https://discord.gg/luminai"

hi this discord link is disactivated.

what's the best practice to use a default 3rd party url to host this project, user should ready to chat when first enter the website.

**Comment by sceuick** [comment]
Thanks for letting me the discord link no longer works. I'll update it.

This particular problem is on my todo list. I intend to solve this in a couple of different ways. I've put this off until I needed it.
I'll track this is a feature request.

**Comment by sdrakulich** [comment]
the discord invite link still doesn't work

**Comment by sceuick** [comment]
Try https://agnai.chat/discord

**Comment by sdrakulich** [comment]
still doesn't work, make a new one, but click that tiny text at the bottom for "Edit invite link"

**Comment by sceuick** [comment]
Hey there, the admin can now define a "default subscription" which can be used by all users (including guests) if the tier/subscription is level `1` or below.
