### ISSUE TITLE
file can not be last on docker cli

### ISSUE THREAD

**Issue by rondlite** [agnaistic/agnai#5]
Small typo in the instructions, order of the options is not correct:

`Run: docker compose -p agnai up -d -f self-host.docker-compose.yml`

gives flag -f error (up needs to come after the options)

should be:

`Run:  docker-compose -p agnai -f self-host.docker-compose.yml up -d`

**Comment by sceuick** [comment]
Cheers, will fix it shortly :smile:

**Comment by sceuick** [comment]
Readme updated :+1:
