### ISSUE TITLE
Bug: Claude Stream Response not working

### ISSUE THREAD

**Issue by PassTheNirvana** [agnaistic/agnai#507]
**Describe the bug**
Claude streaming doesn't work.

**To Reproduce**
1. Start chat with a Claude preset that has Stream Response enabled.
2. Send character a message.
3. Wait for reply.
4. Receive full response with no token streaming,

**Expected behavior**
I expect the response tokens to be streamed with Stream Response enabled.

**Screenshots**
![ezgif-2-ece468c860](https://github.com/agnaistic/agnai/assets/139516371/3c4cbe10-f45e-486c-98c2-e045d5e82b82)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox

**Comment by PassTheNirvana** [comment]
@nai-degen I saw you implemented the streaming. I found this from Anthropic: https://github.com/anthropics/anthropic-sdk-typescript

**Comment by khanonnie** [comment]
I will try to fix this during the next few days.

**Comment by khanonnie** [comment]
@PassTheNirvana I wasn't able to look into this but it seems like @sceuick might have found the issue, the `stream` option was possibly being disregarded in some circumstances which is why it'd just return the full message instead of streaming it. Give it a shot

**Comment by PassTheNirvana** [comment]
> @PassTheNirvana I wasn't able to look into this but it seems like @sceuick might have found the issue, the `stream` option was possibly being disregarded in some circumstances which is why it'd just return the full message instead of streaming it. Give it a shot

Works!
