### ISSUE TITLE
How to use memory books

### ISSUE THREAD

**Issue by BadKid90s** [agnaistic/agnai#537]
Please ask questions on Discord! https://agnai.chat/discord
I have configured a memory book, but it cannot be triggered when I am chatting
![image](https://github.com/sceuick/agn-ai/assets/44721378/8cacef21-cb7e-4c0c-ac30-e548ea302871)
![image](https://github.com/sceuick/agn-ai/assets/44721378/26a22bf2-a5d4-4196-95f4-03e8e6d74f80)

May I ask how to use memory books

**Comment by sceuick** [comment]
This might be an issue with language. I'll look into this.

**Comment by BadKid90s** [comment]
有没有详细的使用教程吗？比如怎么配置能触发记忆书

**Comment by BadKid90s** [comment]
> 这可能是语言的问题。我会调查一下。

Do you have a detailed tutorial on how to use it? For example, how to configure it to trigger a memory book

**Comment by BadKid90s** [comment]
> 这可能是语言的问题。我会调查一下。

Do you have a detailed tutorial on how to use it? For example, how to configure it to trigger a memory book

**Comment by sceuick** [comment]
I've gone through and fixed some bugs that may have caused this issue with memory books. Feel free to re-open if it's still occuring.
