### ISSUE TITLE
Feature Request: Prefilling for Claude

### ISSUE THREAD

**Issue by GuyfromGit** [agnaistic/agnai#552]
Hello, I would like to suggest a way to add prefilling when using Claude on Agnai.
Currently, SillyTavern implemented its own prefilling and it's shown to be really useful at molding the AI's responses to your liking, including in jailbreak use. 
As such, I think that adding a way to send a prefilled message when using Claude would be extremely useful when using it with Agnai.

**Comment by sceuick** [comment]
Claude now has prefill in presets.
