### ISSUE TITLE
In-chat menus don't work

### ISSUE THREAD

**Issue by severedisrepair** [agnaistic/agnai#560]
When in a chat with any bot, I can't seem to open the menus to, for example, edit the character or change preset or memory book. I also can't open the menu that would let me generate more or make the bot respond again. The issue started today, I had no trouble yesterday. I tried clearing cookies and browser cache, but neither helped.

I'm using a Windows desktop. I tried both Brave browser Version 1.56.20 Chromium:115.0.5790.171 as well as Firefox Version 116.02

**Comment by sceuick** [comment]
Hopefuly this is all resolved now. I had to make some changes to decrease payloads for listing pages which naturally caused issues elsewhere across the site.

**Comment by severedisrepair** [comment]
Looks to be fixed now, yeah.
