### ISSUE TITLE
KoboldAI direct connection

### ISSUE THREAD

**Issue by rondlite** [agnaistic/agnai#58]
When using KoboldAI (not horde), I get a service unavailable error when a message is already being processed for another client.
I guess it would be feature request, but could the messages that goto non-horde services have a local queue (redis?)
Or should I change something on my KoboldAI client?

**Comment by ewof** [comment]
maybe a simple retry by a user configurable time (5s by default idk) when kobold says another message is being processed until it goes through?

**Comment by sceuick** [comment]
It could be done using an internal queue. It'd be a fair amount of work and I likely wouldn't use it on agnai.chat.
As you said it'd probably be a good idea to leverage Redis or Mongo as the backend for the queue to ensure the memory usage doesn't increase.

**Comment by rondlite** [comment]
i went the 'easy' route and used a private horde install
