### ISSUE TITLE
Failed to generate response: Kobold request failed: Unprocessable Entity

### ISSUE THREAD

**Issue by Shimmyshak** [agnaistic/agnai#582]
[This individual](https://www.reddit.com/r/AgnAIstic/comments/14fh4bl/site_erases_api_from_kobold_url/) as well as i are still experiencing this isssue. I'm running koboldAI locally with remote_play.bat and pygmalion-1.3b. I experience this issue when running AgnAI locally and on the website.
![image](https://github.com/agnaistic/agnai/assets/71646802/04719e1c-b99d-497d-9866-73aa348e7ae5)
![image](https://github.com/agnaistic/agnai/assets/71646802/95e48258-af6c-4755-a8c3-c662309aa351)

To reproduce, set kobold-compatible or 3d party link to a kobold server hosted with remote-play.bat, then try and generate a message.

**Desktop**
 - OS: Windows 10
 - Browser: Firefox
 - Version v.2fd8eb7

**Comment by sceuick** [comment]
Do your Kobold logs provide any more information? It may provide information as for what part of the entity is unprocessable.

**Comment by Shimmyshak** [comment]
![image](https://github.com/agnaistic/agnai/assets/71646802/38ea4f60-b92d-4f31-8687-b8426b3193cf)
it merely says "Client connected!" and attempting to generate a response yields nothing in the console.

**Comment by sceuick** [comment]
I've made some adjustments to the sampler order parameters. Let me know if it's still an issue.

**Comment by sceuick** [comment]
Assuming this is resolved.
