### ISSUE TITLE
NSFW

### ISSUE THREAD

**Issue by Yone09** [agnaistic/agnai#59]
Can you make the NSFW content allowed ?

**Comment by sceuick** [comment]
There isn't anything prohibiting NSFW. If you're referring to the OAI gaslight for Turbo, you can adjust it freely.
I will be publishing a new default OAI preset with a different gaslight with a release hopefully going out today.

**Comment by Yone09** [comment]
I adjusted it to make NSFW content allowed but I still get the massage that the AI can’t continue this role playing

**Comment by sceuick** [comment]
That will be specifically to do with the AI service you're using. I'd keep experimenting with your `gaslight` and `scenario`.
Sorry I couldn't be of more help.
