### ISSUE TITLE
Tag filter

### ISSUE THREAD

**Issue by severedisrepair** [agnaistic/agnai#593]
This is a minor one, but whenever I open https://agnai.chat/character/list, the tag filter only shows "imported", "nsfw" and "archived" (since I don't have any characters with those tags, it makes it do nothing. Switching to, for example, https://agnai.chat/chats and then back to the character list fixes it, letting me see and filter my own tags. The issue returns if I refresh the page. So, yeah, nothing site-breaking, just a bit of a detour.

I'm on desktop.
OS: Windows 10
Browser: Brave Browser, Version 1.57.53 Chromium: 116.0.5845.114 (Official Build) (64-bit)

**Comment by sceuick** [comment]
Fix coming for this in the next day or so.
