### ISSUE TITLE
Trouble connecting with own Kobold Instance

### ISSUE THREAD

**Issue by rondlite** [agnaistic/agnai#6]
I got my own KoboldAI instance and when I use it with TavernAI, it is all good. No issues.
When I use with agn-ai, I only get one message back (if I am lucky) and after that it stalls.
No more responses, not even when refreshing page or starting new chat, other character, nothing anymore.
If I set agn-ai to horde, there is no issues.

I checked on the Kobold side and the message is coming in, will further debug by adding some logging in the adapter.

Any suggestions?

**Comment by sceuick** [comment]
Agnai is completely silent after making the request?
It might be worth logging the request being sent the Kobold to make sure it's completely valid and expected.

**Comment by rondlite** [comment]
I added an else statement in kobold.ts#56 and added a logger.error under there, 
indeed it is the cause.

trimming fails.

```
[api] [2023-03-08T01:12:49Z] ERROR (app/28562): Trimming failed
[api]     err: {
[api]       "results": [
[api]         {
[api]           "text": "   Oh, okay. So, I'll start with the time you worked here.\n\n*sips tea*\n\nHmm... let's see... Let's see... Let's see... I was built in July of this year, and I was launched in May of this year.\n\nThat gives us a total of 434 days, which works out to be around 12."
[api]         }
[api]       ]
[api]     }
```
will now check the `trimResponse` function to see why

**Comment by sceuick** [comment]
My guess is it doesn't find an end token. I return `void` instead of just returning all of the text.
Change line 31 in `srv/api/chat/common.ts` to:
```ts
  if (trimmed.index === -1) {
    return { index: -1, response: generated.trim() }
  }
```

**Comment by rondlite** [comment]
that's exactly it, i was just looking at the same thing, another observation in that file is that the sanitise would not trim at the beginning and the end (join) 
So maybe adding `const trimmedGenerated = generated.trim();` at the top there and use `trimmedGenerated` further down instead of `generated`

*ashamed for not making a PR*

my issue is solved 😎
(indeed no matching end token)


update: if text start with quotes it still fails
`  "text": " \"Well,  `
chat/common.js#42: 
 `return generated.replace(/\s+/g, ' ').replace(/\\"/g, '').trim()`
 
 fixes it

**Comment by sceuick** [comment]
Ah, interesting! I definitely wouldn't have expected quotes to matter...
I'll definitely look into that. They should definitely be allowed.

**Comment by sceuick** [comment]
Ah, interesting! I definitely wouldn't have expected quotes to matter...
I'll definitely look into that. They should definitely be allowed.

**Comment by rondlite** [comment]
turns out it was not the quotes, I removed the `trimmedGenerated` thinking that your fix was enough, but seems it is needed. White space at the beginning..

next issue is that my kobold returns an empty line in between responses, this is not picked up and the output is different results which make no sense since they all different options, might need to tweak kobold itself.

**Comment by rondlite** [comment]
Ok, I think I figured it out, the newly added trim function (that was needed to trim white space at beginning and end) was also causing `\n\n` to be filtered out, it turns out that is my actual END_TOKEN ! 
Can you have a look if you happy with this?
It solved it for me.. (i can make PR if you want)

```
import { AppSchema } from '../../db/schema'

/**
 * A single response can contain multiple end tokens
 *
 * Find the first occurrence of an end token then return the text preceding it
 */
export function trimResponse(
  generated: string,
  char: AppSchema.Character,
  members: AppSchema.Profile[],
  endTokens: string[]
) {
  const baseEndTokens = [`${char.name}:`, `${char.name} :`, 'END_OF_DIALOG', '<END>','\n\n']
  const placeholder = 'NEWLINE_PLACEHOLDER'
  const trimmedGenerated = generated.replace(/\n\n/g, placeholder).trim().replace(new RegExp(placeholder, 'g'), '\n\n')
  for (const member of members) {
    baseEndTokens.push(`${member.handle}:`, `${member.handle} :`)
  }

  const trimmed = baseEndTokens.concat(...endTokens).reduce(
    (prev, curr) => {
      const index = trimmedGenerated.indexOf(curr)
      if (index === -1) return prev
      const text = trimmedGenerated.slice(0, index)
      if (prev.index === -1) return { index, response: text }
      return index < prev.index ? { index, response: text } : prev
    },
    { index: -1, response: '' }
  )

  if (trimmed.index === -1) {
    return { index: -1, response: trimmedGenerated.trim() }
  }
  return trimmed
}

export function joinParts(parts: string[]) {
  return parts.map(sanitise).join(' ')
}

export function sanitise(generated: string) {
  return generated.replace(/\s+/g, ' ').trim()
}
```

**Comment by sceuick** [comment]
I wonder if we can just `.trim()` just before returning and add `\n\n` to the baseEndTokens.
Have a squiz at #10 and let me know what you think.
