### ISSUE TITLE
User default preset no longer selected when creating a chat

### ISSUE THREAD

**Issue by cousincrusher** [agnaistic/agnai#608]
**Describe the bug**
The chat creation page's preset field is populated with `[Agnaistic] Agnaistic (Built-in)` instead of my default preset.

**To Reproduce**
1. Create a chat, it can be from `/chats` or from `/character/{charaId}/chats`
2. The chat creation page's preset field is populated with `[Agnaistic] Agnaistic (Built-in)` instead of my default preset.

**Expected behavior**
 The chat creation page's preset field is populated with my default preset.

**Desktop (please complete the following information):**
- Windows, Chrome

**Smartphone (please complete the following information):**
- N/A

**Comment by sceuick** [comment]
Fix incoming.
