### ISSUE TITLE
Why use token budget? 

### ISSUE THREAD

**Issue by ghost** [agnaistic/agnai#624]
Please ask questions on Discord! https://agnai.chat/discord
Hi, 
I'm not sure i understand what the purpose of token budget is. Why does this exist?

**Comment by sceuick** [comment]
Hi,
The AI models can only provided so much context before they either:
- throw an error
- return complete garbage

Each model/service has context (token) constraints we need to work within so provide budgets for various aspects of the prompt to include as much room as possible for conversion history after including the information about the character(s) and the scenario.

**Comment by ghost** [comment]
Thanks @sceuick - we had somebody else face a similar issue and wrote a token trimming helper function for this - https://github.com/BerriAI/litellm/blob/775932a4ccd2c6488779c1e0541e8234d55329b4/litellm/utils.py#L2748

Is this good enough for your use-case?

**Comment by sceuick** [comment]
You might need to be specific with your original question.
Agnaistic already does trimming where needed to fit as much conversation history into the prompt as possible.

Each prompt sent to the AI contains preamble (System prompt, character information, scenario information) and post amble (what the AI should complete). Once the pre and post amble have been evaluated and token counted, we fill up the remainder of the context limit (budget) with chat history.
