### ISSUE TITLE
Linebreaks

### ISSUE THREAD

**Issue by An0therAnon** [agnaistic/agnai#63]
For some reason agnai doesn't receive line breaks, its quite annoying when using a RPG bot with stats which are all clogged in a sole paragraph. Even with other bots, when looking at the original result in scale, it haves line breaks, but in the UI it doesn't.

**Comment by sceuick** [comment]
This might be due to the "end tokens" that Agnai looks for in a response because it expects it to be conversational in nature.
Specifically, Agnai looks for `\n\n` which might be causing your issue.

I'm intending to support other modes such as adventure, story, and companion modes.
Your use case might fall in to that.

**Comment by giubil** [comment]
@sceuick I took a look at the issue of the linebreaks disappearing in a message, and I think I found the the problem. 

It's coming from the `sanitise()` function in `srv/api/chat/common.ts` : 
https://github.com/luminai-companion/agn-ai/blob/760260e990efdd82431dcbdcf45f82ad0cf02587/srv/api/chat/common.ts#L99

In regex, `\s+` will match all whitespaces, _including_ line breaks. To exclude linebreaks from the match, you need to use this regex : `/[^\S\r\n]/g` (which also excludes Windows carriages returns for good measures)

I've tested it locally, and indeed, when replacing the regex with the updated one, we see line breaks in the received message : 

![CleanShot 2023-03-22 at 20 18 23](https://user-images.githubusercontent.com/9071882/227014121-b4c1f1e6-2930-48bd-9360-be64ac295f0f.png)

I haven't done any more testing than this, so I have no idea if it breaks something somewhere else, but thought I would share anyways.

**Comment by sceuick** [comment]
Thanks for digging into this for me. I'll do some testing with your regex.

**Comment by An0therAnon** [comment]
Welp, it there is another issue which wasn't in the site before; ill post it here since its quite similar and maybe it haves a relation: when a message have a double linebreak it will cut the message at that, doesn't receive the full message.

**Comment by sceuick** [comment]
Literally just deployed a change that removed the `\n\n` end token. :crossed_fingers:

**Comment by An0therAnon** [comment]
Just tested, everything in order. Good shit man, hope you can keep the good work.

**Comment by An0therAnon** [comment]
Just tested, everything in order. Good shit man, hope you can keep the good work.
