### ISSUE TITLE
can i request myself model api？

### ISSUE THREAD

**Issue by Dhaizei** [agnaistic/agnai#632]
Hello, can you access the fine-tuned model with this repository after running it? Or can you access an API for your own trained model? I'm not very familiar with this program, so I hope you can explain.

**Comment by sceuick** [comment]
Agnaistic doesn't provide any tooling to run models.
However you can use tools such as Llama.cpp, KoboldCpp, Oobabooga text generation webui, Kobold to run a local model and Agnaistic can be configured to talk to the tool running your local model.
This is done by creating a preset using the "Third Party" AI service and entering the URL for your server (I.e., localhost:[port] if you're self-hosting Agnai or a LocalTunnel URL if you're using Agnai.chat).

I hope this helps.

**Comment by Dhaizei** [comment]
thanks a lot.   So what are the parameters of this access, what is the content of the request to access the third party address, and how do I write the corresponding content? Also, I filled in the key, but it was wrong.OpenAl 
 request failed : socket hang
