### ISSUE TITLE
[Bug] Web speech synthesis is not available under Linux and Firefox.

### ISSUE THREAD

**Issue by KometFox** [agnaistic/agnai#633]
**Describe the bug**
I am trying to use the Web Speech Synthesis for my character but the button for changing voices is stuck in "Voices Loading..."  So I have no idea what I am supposed to do now. I am supposed to install a voice system for my Linux OS or is there a web browser plugin for Firefox? 

**To Reproduce**
Go to the Character advanced mode and use the Web Speech Synthesis. 

**Expected behavior**
A method for selecting voices using Web Speech Synthesis for each character. 

**Screenshots**
![Bildschirmfoto_2023-09-20_07-39-56](https://github.com/agnaistic/agnai/assets/14570163/ce5a4182-d4bf-49e8-a091-ce46444af733)

**Desktop (please complete the following information):**
 -Linux Xubuntu 22.04 x86_64 bit
 -Firefox 117.0.1 (64-Bit)
 -Librewolf 117.0-1 (64-Bit)

**Comment by LamaSlayer14** [comment]
I have the same problem

**Comment by cingorn** [comment]
The PR above should fix the loading issue in FF, however on Linux the voices might need to be installed separately and enabled for the browser. There are lots of issues on different platforms with Web Speech API, so YMMV.
