### ISSUE TITLE
Unhandled rejection

### ISSUE THREAD

**Issue by M-a-r-c-y** [agnaistic/agnai#642]
**Describe the bug**
As written in the Pipeline guide, I installed agnai through terminal, then started it with --pipeline, but I got an unhandled rejection. 

Full message:
**PS G:\Games\agnai-dev> npm install agnai -g

changed 329 packages in 2m

23 packages are looking for funding
  run `npm fund` for details 
      
PS G:\Games\agnai-dev>  agnai --pipeline
Installing pipeline features... This may take some time
python3 -m venv C:\Users\musta\.agnai\pipeline
Python 
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "9009".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v18.18.0**

**To Reproduce**
1. Open Visual Studio Code
2. Open new terminal
3. npm install agnai -g
4.  agnai --pipeline

**System**
Windows 10
Python 3.11.5
Node JS v18.18.0

**Comment by M-a-r-c-y** [comment]
Maybe I didn't understand clearly how this works? I just followed the steps of this guide: https://agnai.chat/guides/pipeline
Installed NodeJS, updated Python, ran the commands. 
I did try to download the project itself and then ran it all again from its folder, that didn't work either.

**Comment by sceuick** [comment]
Hey there, I haven't looked at the pipeline stuff for quite a while.
I'll definitely look into this when I can.

**Comment by M-a-r-c-y** [comment]
Okay thanks. please let me know if you find anything.

**Comment by cingorn** [comment]
@M-a-r-c-y This might be due to the tool invoking `python3` command, which is not added by Python on windows. Solution described here:
https://superuser.com/questions/1576758/how-do-i-alias-python3-on-windows

Also: don't upgrade to Python 3.12 yet, most of the libraries that the tool uses don't work on 3.12 yet.

**Comment by M-a-r-c-y** [comment]
@cingorn Thank you!
