### ISSUE TITLE
Pipeline 

### ISSUE THREAD

**Issue by AcyTheWeirdAce** [agnaistic/agnai#654]
Hello. I am using windows 11 and opera gx browser...i was using sillytavern for a while and decided to move to agnaistic. I have been trying to get the pipeline to work but i get some directory path and then "system couldnt find especified path"

**Comment by tohurtv** [comment]
I have a pull request for a fix for the pipeline running on windows https://github.com/agnaistic/agnai/pull/651 just apply the fix manually until it gets merged

**Comment by AcyTheWeirdAce** [comment]
Hi. "apply the fix manually"? what do you mean?

**Comment by tohurtv** [comment]
You will have to apply the changes I made in that pull request to your package.json in your agani folder in order for the pipeline to run on windows

**Comment by AcyTheWeirdAce** [comment]
Well, i will try it out. Thanks

**Comment by tohurtv** [comment]
oh also you going to need to go to your python install folder in appdata/local/programs and copy the python.exe to python3.exe .. copy don't rename the original but copy as you need both python.exe and python3.exe as there are hard coded paths for python3 due to linux
