### ISSUE TITLE
Temporary dialogue examples

### ISSUE THREAD

**Issue by gtaltatra** [agnaistic/agnai#67]
Tavernai has an additional field for bot definitions, which is used for example dialogs. But unlike the "Sample Conversation" from Agnai (i presume), this field get overridden by context memory when it reaches its limit. Which, in my opinion, is pretty smart. 
But example dialogs aren't the only thing the user might want to make temporary. For example, this field can be used for various kinds of details that might be important for a particular scenario but useless for another. Or, for example, include additional characters that user may want to include or exclude depending on scenario.
I think it would be great to adapt this feature from Tavernai and extend its functionality for using defs as well

**Comment by sceuick** [comment]
> Optionally exclude sample chat

Yup, this will be coming with prompt options

> For example, this field can be used for various kinds of details that might be important for a particular scenario but useless for another. Or, for example, include additional characters that user may want to include or exclude depending on scenario

Could you provide some examples of this?

**Comment by gtaltatra** [comment]
>Yup, this will be coming with prompt options

I mean not exclude but override with context memory. If that's what you mean.
>Could you provide some examples of this?

Like I said, any additional characters. For example, a bot may have a friend or some kind of companion with the ability to influence events in a certain way. And the user may be interested in the reaction of the bot to interact with this character within a certain scenario.
As for the details, here you can think of anything you want. Any details that are important to the character, but only within a certain scenario. Well, I don’t know, for example, information about what weapons Samus Aran wears and a detailed description of her abilities for rp within which this is important. 
On the other hand, it's probably worth acknowledging that copying a character is probably more functional in this regard, Its just that I often use short scenarios with huge amount of swipes and I thought it will be easy enough to expand it e.g:
START /// you may remove this line if you have no examples
DIALOGUES
Temporary_defs  /// you may remove this line if you have no temporary defs
DEFS

**Comment by sceuick** [comment]
Is this something that is suitably solved by memories + prompt options?
I.e., configuring memories to appear toward the bottom of the prompt.

**Comment by gtaltatra** [comment]
Temp defs? Yes, I guess even current realization combined with the new option to label clones is enough already. 
This issue was mainly about temporary dialogue examples anyway.
