### ISSUE TITLE
Third Party CLAUDE doesnt work.

### ISSUE THREAD

**Issue by esthein** [agnaistic/agnai#695]
Apparently Claude doesnt work when using Third Party. 
After setting the URL, the format and password in the Settings for claude, correctly, in PRESETS i run into some issues.
Choosing any Claude Model option in presets causes this message to come:
Failed to generate response: Claude request failed: Not Found

In the huggingface, the url should give me access to the following models: 
allowedModelFamilies: turbo,gpt4,gpt4-32k,gpt4-turbo,claude,bison,aws-claude

And if i try to use gpt4, it works! The only one that doesnt is Claude.

**Comment by khanonnie** [comment]
Add /v1/complete to the end of the third-party URL and it should work.
