### ISSUE TITLE
Support Windows Installation

### ISSUE THREAD

**Issue by MarkSchmidty** [agnaistic/agnai#7]
Windows manually installation fails with `'NODE_ENV' is not recognized as an internal or external command`

![image](https://user-images.githubusercontent.com/5949853/223588591-ffc2ad05-949e-4b35-b34d-986484e81e29.png)

(Side note: The readme.md says to run `npm build:all` which is not a valid npm command. The correct command is `npm run build:all`)

**Comment by sceuick** [comment]
Thanks for the issue. I can't boot into Windows at the moment, can you test this for me:
```sh
# compile front-end
set NODE_ENV=production && parcel build web/index.html --no-optimize --detailed-report
# compile back-end
npm run build:server
# run everything
set NODE_ENV=dev && concurrently -c auto -n web,api,tsc \"parcel web/index.html --no-cache\" \"npm run server:watch\" \"npm run build:server:watch\" 
```

**Comment by MarkSchmidty** [comment]
The syntax to set an environmental variable in windows is `setx ENV_VAR "Variable Content"`
![image](https://user-images.githubusercontent.com/5949853/223601214-6b392236-e75b-411c-a73a-f56b82673ec7.png)
`setx NODE_ENV "production"` works but `parcel build web/index.html --no-optimize --detailed-report` throws:
```
'parcel' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by sceuick** [comment]
Ah, my bad, should be `npx parcel ....`

**Comment by sceuick** [comment]
I've updated the scripts. Let me know if they work otherwise I'll test them when I'm next using Windows.

**Comment by sceuick** [comment]
Seems some people are installing okay on Windows. I'll close for now.
