### ISSUE TITLE
Character hub downloads failing

### ISSUE THREAD

**Issue by severedisrepair** [agnaistic/agnai#702]
When I try to import a character from Chub, it fails to do so, giving the message: "Character Hub download failed: Failed to fetch". I don't know if the problem is on Chub's side or Agnaistic's.

Windows Desktop. Brave Browser
[Version 1.60.118 Chromium: 119.0.6045.163 (Official Build) (64-bit)]

**Comment by sceuick** [comment]
This appears to be resolved.
