### ISSUE TITLE
Multiple greetings selection bug

### ISSUE THREAD

**Issue by chadfurman** [agnaistic/agnai#734]
As reported here: https://discord.com/channels/1075959979942625291/1097328983927955546/1182332612459626516

Describe the bug:
I think there might be an issue in web version of Agnai. When I download and import a character with multiple greetings, swiping between them does not work correctly - 2nd greeting appears to be the same as 1st, until I confirm the swipe, only then all 3 are visible.

With cards with multiple greetings, in first message, when I click on the "arrow" to pick between greetings, the 2nd greeting appears to be the same as 1st.

There is no error displayed, and when I confirm the change of greeting, and want to change it again, all greetings are visible.

OS - Windows, Mozilla browser version

**Comment by sceuick** [comment]
I believe this has been resolved.
