### ISSUE TITLE
AI Horde API Settings

### ISSUE THREAD

**Issue by nednaZ** [agnaistic/agnai#74]
Browser password saving will try to insert your site login as the AI Horde API key.
If this ever gets mistakenly saved, it you have to manually insert '0000000000' to get it to return to anonymous mode.
This is a security risk as it's potentially sending your login as an API key.

**Comment by sceuick** [comment]
Thanks for the heads up, will sort that out.

**Comment by sceuick** [comment]
Should be fixed. Disable auto-complete on the settings form.
