### ISSUE TITLE
Example dialogue is removed from prompt once context limit is reached

### ISSUE THREAD

**Issue by kon1ee** [agnaistic/agnai#755]
**Is your feature request related to a problem? Please describe.**
Example dialogue should be used to teach your character how to speak, but still stays in the prompt even when the context limit is reached. At this point, it wouldn't be needed, since the bot would have already used the dialogue and copied the style. For characters with a generous amount of example dialogue, this wastes tokens that could be better used for the chat history.

**Describe the solution you'd like**
It would be great if when the prompt reaches the context limit, example dialogue is removed from the prompt sent in favor of chat history.

For example: The chat context limit is 8k. There's 1k tokens of example dialogue, 1k of memory, 1k of character personality, and 5k left for chat history. A 200 token size message is added to the chat. There would now be 800 tokens of example dialogue and 5.2k tokens of chat history. This would continue until there are 0 tokens left in the example dialogue sent in the prompt, giving chat history a total of 6k tokens instead of 5k.

**Describe alternatives you've considered**
Manually removing the example dialogue once the chat context limit is reached in the "edit chat" menu.

Duplicating the preset and removing {{example_dialogue}} from the prompt altogether.

**Additional context**
Not sure if this is something that already happens, but isn't happening for me because I have my memory context set to 4k?
If that's the case, wouldn't it still be better to prioritize the chat history once the context limit is reached?

**Comment by sceuick** [comment]
This should already be the case. If the example dialogue isn't being automatically removed then it's a bug.
