### ISSUE TITLE
Impersonated Character Characteristics being Copied by Main Bot

### ISSUE THREAD

**Issue by catofwonders** [agnaistic/agnai#756]
Bug Description:
When impersonating a character, sometimes the main bot will steal or copy unique characteristics of the impersonated character as if they were from its own Persona. 
Example: "John makes everyone around him feel the urge to laugh". In this example John is the impersonated character and Mickey is the main bot, in the chat the following will usually happen "John feels an urge to laugh because of Mickey's power". 
Prompt Template Used:
Validated and Modified version of Vicuna's default  template. 
Template used:
{{#if system_prompt}}{{system_prompt}}
{{/if}}
Below is an instruction that describes a task. Write a response that appropriately completes the request.

Write {{char}}'s next reply in a fictional roleplay chat between {{#each bot}}{{.name}}, {{/each}}{{char}}. Be descriptive and lengthy in the responses.

{{char}}'s Persona: {{personality}}

{{#if memory}}{{char}}'s Memories:
{{memory}}
{{/if}}
{{#if scenario}}This scenario of the conversation: {{scenario}}
{{/if}}
{{#if example_dialogue}}This is how {{char}} should talk: {{example_dialogue}}
{{/if}}
Then the roleplay chat between {{#each bot}}{{.name}}, {{/each}}{{char}} begins.
{{#each msg}}{{#if .isbot}}ASSISTANT:
{{.name}}: {{.msg}}{{/if}}{{#if .isuser}}USER:
{{.name}}: {{.msg}}{{/if}}
{{/each}}
{{ujb}} 

{{user}}'s personality: {{impersonating}}

ASSISTANT: {{post}}. 

Additional Info: The impersonated character in question utilizes key attribute method, no macros were used in the keys, instead the name of the character was used. the attributes were as follows:
personality:
backstory:
appearance:
attributes:

**Comment by sceuick** [comment]
This is a model issue. I'd remove the personalities of the non-responding characters if the model you're using can't distinguish between the personality definitions.
