### ISSUE TITLE
Inability to edit temp characters in a chat from the edit character screen

### ISSUE THREAD

**Issue by kon1ee** [agnaistic/agnai#764]
**Describe the bug**
Temporary characters aren't able to be edited through the edit character screen in chat. Only through the participants screen.

**To Reproduce**
1. In an open chat with a temporary character, click the top right •••
2. Click on Character
3. Select the temporary character from the drop-down under edit character.
4. Try to edit the character and click update.
5. When clicking update, nothing happens.

**Expected behavior**
Character should update.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 12T
 - OS: Android
 - Browser: Chrome
 - Version: No clue sorry

**Comment by sceuick** [comment]
I don't believe this is currently an issue, so closing for now.
