### ISSUE TITLE
NovelAI Api Bug

### ISSUE THREAD

**Issue by MickeyAdaptus** [agnaistic/agnai#769]
So i am using an novelai subscription api key on agnai, and am trying to chat with a character i made, but the responses come off as short and even quite bland, even tough i put prompts in the character's editing to make it act creative with its writing.

I've had this problem on sillytavern as well, and am not quite sure if i am doing something wrong, but someone told me they were having a similiar problem, so i was told to post about it here.
![Iroh bug](https://github.com/agnaistic/agnai/assets/154277800/586c3781-e0c0-46d6-b886-7986f0f986c8)

Im using agnai on a browser named using Mozilla Firefox  120.0.1, and my IOS is Windows 10.

**Comment by sceuick** [comment]
Provided your prompts look fine (see the message metadata using the `(i)` button) then this can only really be a problem with the model.
