### ISSUE TITLE
Multiple memory book items with the same name appear after a modification

### ISSUE THREAD

**Issue by desiato4711** [agnaistic/agnai#770]
**Describe the bug**
When I edit a memory book by changing its content and then safe it, I will often get multiple entries of the same item in one book. For example when I add something to an entry, I will get the old and the new version in one book and I have to delete the old version manually.

**To Reproduce**
1. Go to a memory book
2. Add something to an entry and save
3. Change sorting into  title and then back to date
4. Multiple entries show up.

**Expected behavior**
I only want to have the edited version after a modification

**Comment by sceuick** [comment]
I believe this has been resolved.
