### ISSUE TITLE
    npm install -g pnpm 

### ISSUE THREAD

**Issue by desiato4711** [agnaistic/agnai#774]
**Describe the bug**
6. From inside the cloned/unpacked folder in your terminal/console:
    npm run deps
    npm install -g pnpm                                                                                   <<<<<<<<<<<<<< this is needed too
        * Do this every time you update AgnAI, just in case.
        * This will install the dependencies using pnpm v8

**To Reproduce**
Follow the "Running Manually" instructions in README.md

**Comment by sceuick** [comment]
Installing `pnpm` globally isn't required. The `npm run deps` script uses `npx` which accomplishes something similar to installing it globally.
