### ISSUE TITLE
Context massively underfilled on Self-host / 3rd Party Service setting

### ISSUE THREAD

**Issue by dordle** [agnaistic/agnai#776]
**Describe the bug**
As a local user, practical context sent appears to top out at somewhere below 4096 tokens because of the subscriber limit for either the Llama.cpp or KoboldCpp adapter set through the Self-host / 3rd Party service selection in a Preset (tested both, have not tested other adapters, though they may also be affected). Problem does not occur with Textgen, untested with Horde. This shouldn't happen when hosting locally.

**To Reproduce**
1. Go to Presets
2. Pick "Self-host / 3rd Party service" for Service
3. Pick either "Llama.cpp" or "KoboldCpp" for Adapter
4. Set Max Context Length to higher than 4096; 8192 for all the models I've tested.
5. Send long context exceeding ~4096 toxens either in one message or multiple.

**Expected behavior**
For the posts sent to go through up to the 8192 token limit, after which the oldest posts should be cut.

**Actual behavior**
Posts get cut prematurely to stay somewhere below 4096 tokens, despite a higher max context limit and many more posts being available.

**Desktop (please complete the following information):**
 - OS: Windows x64
 - Browser: Firefox, Chromium; both tested
 - Version: commit 1c7848a

**Additional context**
The Textgen service passes messages properly up to full max context length, although most backends have dropped this API by now. There are other issues concerning the OpenAI adapter not respecting the prompt format at all, but that is for another issue once I test it properly.

**Comment by sceuick** [comment]
This needs some investigating. A brief look at the code shows that self-hosting doesn't have a hard context limit.

**Comment by sceuick** [comment]
Re-open if this is still an issue. I haven't been able to reproduce this.
