### ISSUE TITLE
Steamship support

### ISSUE THREAD

**Issue by An0therAnon** [agnaistic/agnai#78]
Scale is pretty much kill unless you don't care about their new filter, requesting steamship support for access to GPT 4.
I don't know if you can adapt code that is written for Tavern but ill drop it here to see if it can help.
rentry.org/spermshipeng

**Comment by sceuick** [comment]
Looks like it also went the same way as Scale.

**Comment by John542-alt** [comment]
I would be very happy if the Agnai had a Steamship ,_,

**Comment by sceuick** [comment]
Is this still something people want? With the mandatory filtering now in place, I'm guessing that there's no demand for it anymore?

**Comment by gtaltatra** [comment]
No, spermship was never an option, too small to sustain.
