### ISSUE TITLE
Persistent volume permission

### ISSUE THREAD

**Issue by sandwichdoge** [agnaistic/agnai#79]
At the moment, self-host.docker-compose.yml mounts **/app/dist/assets** to **/dist/assets** on host machine. There's a few problems I've observed:
- Permission issues if the current user is not allowed to create files in root dir.
- Straight up doesn't work if you use Docker for Windows, you lose all character avatar assets.

Proposed fix, allow Docker to manage that dir as a persistent volume.
- In Dockerfile, add line `VOLUME [ "/app/dist/assets" ]`
- Remove these lines in self-host.docker-compose.yml:

```
volumes:
    - /dist/assets:/app/dist/assets
```
I can make a PR if this looks good.

**Comment by sceuick** [comment]
Yah, totally happy to accept a PR for this.

**Comment by sandwichdoge** [comment]
I opened a PR, this should fix the problem in the OP, but users will lose their current assets after the change is applied.

**Comment by sceuick** [comment]
Thanks for raising the PR.
