### ISSUE TITLE
GENERATE button - Wipes TAGs entry field

### ISSUE THREAD

**Issue by Judas87Swiff** [agnaistic/agnai#791]
**Describe the bug**
When using the Auto-Generate AI character form creation buttons, they overwrite the TAGs section, leading to any entered TAGs being removed even though the AI never fills out the TAGs section.

**To Reproduce**
1. Press 'Generate'.
2. Wait.
3. See any entered TAGs removed/deleted.

**Expected behavior**
To not have entered TAGs removed especially for the 'Generate' buttons that are lower down vs the highest one, which overrides everything.

Version: The Mobile web browser version.

**Comment by sceuick** [comment]
Should be fixed now.
