### ISSUE TITLE
Keep a history of generated character images

### ISSUE THREAD

**Issue by AllesMeins** [agnaistic/agnai#796]
**Is your feature request related to a problem? Please describe.**
If you already have a generated image for your character generating a new one always feels like a gamble, because you might get one you like better - but you also might get one that is worse and the old one is forever lost.

**Describe the solution you'd like**
Keep a history of the generated images (in this session) so you can go thru them and select the one that you like the most. Ideally with the option to download the images if you happen to have more than one that you like.

**Comment by sceuick** [comment]
Completed
