### ISSUE TITLE
[Bug Report] Unable to Scroll far enough to reach characters in large group chat

### ISSUE THREAD

**Issue by LordTyrionSeptim** [agnaistic/agnai#802]
**Describe the bug**
Unable to scroll far enough to reach some characters in a large group chat(around 7 to 8+ characters). Can't reach the characters icon in the participant bar, so cannot get them to respond. This is true on both mobile and pc for Agani web version, not sure about local.

**To Reproduce**
1. Go to participants
2. Add 8+ characters just to be sure
3. Scroll to the side of the participants bar as far as you can
4. See that there are still some characters you cant reach after scrolling as far as you can

**Expected behavior**
You will scroll to the side and be unable to reach some characters in a group chat, rendering them unable to participate

**Screenshots**
![Screenshot_2024-01-09_212016](https://github.com/agnaistic/agnai/assets/113543267/c76f9a05-068a-41fd-a1e4-05584873cd85)

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: Google Pixel 2
 - OS: Android 11
 - Browser Chrome
 - Version 120.0.6099.210

**Additional context**

**Comment by sceuick** [comment]
Fix for this coming shortly.
