### ISSUE TITLE
User Personas

### ISSUE THREAD

**Issue by ashton-jiffy** [agnaistic/agnai#804]
**Is your feature request related to a problem? Please describe.**
I’m really interested about a feature that was in Character.ai where you could make your “persona”. But i get it we got one for already-created bots but why not making a alt ego of your profile?

**Describe the solution you'd like**
In the impersonate selection, you would see a second button where you could create your user personas. You could set one of your personas as default for all chats

**Describe alternatives you've considered**
Idk really, my mind couldn’t make something up.

**Additional context**
This request is based of the Character.ai user personas feature: https://book.character.ai/character-book/user-personas

![IMG_1991](https://github.com/agnaistic/agnai/assets/67291514/b30e5ebb-18e7-4d70-8e37-ff17deafb746)

**Comment by sceuick** [comment]
Heya,
The main reason I haven't done this is that the user profile page would need a fair moment of work to support the persona fields.
I'd _prefer_ we continue to use character impersonation and improve their "stickiness" - as in your chats should try to remember the character you last impersonated and automatically switch.

I'm going to mark this as `wontfix` unless there is a very compelling reason to add user personas.

**Comment by ashton-jiffy** [comment]
Oh i see
