### ISSUE TITLE
Generate More button bugs out whole page

### ISSUE THREAD

**Issue by alferitu** [agnaistic/agnai#806]
**Describe the bug**
When using the Generate More function, it seems to prevent editing, deleting  and even the "retry generate more" button until the page is refreshed. The additional content DOES generate, but then the program becomes unusable until the page is refreshed.

**To Reproduce**
1. Click Generate More

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11
 - Any browser

**Smartphone (please complete the following information):**
 - Samsung S23
 - Any browser

**Comment by sceuick** [comment]
Will close this in favour of #793
