### ISSUE TITLE
[request] add Dynamic Temperature sampler

### ISSUE THREAD

**Issue by 2cute4name** [agnaistic/agnai#809]
Since a few other UIs have this sampler now (e.g. SillyTavern, Kobold), I figured it's a good idea to see it on Agnai as well. Dynamic Temperature could be useful because there doesn't appear to be a single temperature suitable for all cases. Right now, I am having to manually adjust the slider a lot. DynTemp could be a solution (or part of it) so I'd like for it to become an option here too, to see if it can work better in my setup. I essentially do it manually anyway at the moment, so it sounds like it'd be a good addition.

**Comment by sceuick** [comment]
This has been added and is available for kobold and aphrodite presets.
