### ISSUE TITLE
OpenRouter LLM parameter support

### ISSUE THREAD

**Issue by VibeCodeBunny** [agnaistic/agnai#819]
OpenRouter has introduced support for LLM parameters. I am not sure if this is on the list already. I could not find it in the backlog, but it would be wonderful to finally get a few more settings for OpenRouter models. While they are pretty cool, I can barely make them work sometimes due to severe repetition.

### **In their announcement on Discord they said this:**

**Repetition penalty**

- This is a popular token penalty that's helpful for many models, including MythoMax and Goliath. Try 1.1.

- New docs section for [LLM Parameters](https://openrouter.ai/docs#llm-parameters), including defaults.
_______

If I missed an existing ticket, I apologize. Thank you for the great work!

**Comment by sceuick** [comment]
This is done.

**Comment by VibeCodeBunny** [comment]
Thank you @sceuick 🙏🏻🎊
