### ISSUE TITLE
Options to backup settings and convos. Option to copy convos. Portable instances?

### ISSUE THREAD

**Issue by gtaltatra** [agnaistic/agnai#83]
Tavernai allows you to do all this with a simple manipulation of files inside your folder. And is portable.
I'm not sure how to do it here. Also I'm afraid its not really possible to run portable instances?

**Comment by sceuick** [comment]
At the moment the only feasible way is backing up your MongoDB data and restoring it.
I generally want to encourage self-hosting and want to lower the barrier for entry for self-hosting.
Some solutions for this for self-hosters are:

1. Exporting and importing your anonymous state. This probably wouldn't been too hard at all and could be implemented very quickly.
2. Using alternate persistence strategies such as JSON files or SQLite. This would be a lot more work as I would have to duplicate my persistence code.

Thoughts?

**Comment by gtaltatra** [comment]
>At the moment the only feasible way is backing up your MongoDB data

Can you please specify which files exactly (if possible)?
>1. 

>2.

I can't say i know the difference, so an easier option would be better I guess. Although having json files and knowing  which one does what exactly looks better, if everything can be done using agnai ui, without managing actual files, there should be no difference.

>anonymous state.

Also regarding this. Is there a way to run it in anonymous state if I already have mongodb files without docker (on windows)?
I tried docker, and 
1. It doesn't allow me to update or downgrade, always loads the same image (using this: compose -p agnai -f self-host.docker-compose.yml up -d) even though I removed the containers and files and ran it in a different folder. 
2. I tried this command (to run without mongodb): docker run -dt --restart=always -p 3001:3001 agnaistic:latest
And it causes this error: 

Unable to find image 'agnaistic:latest' locally
docker: Error response from daemon: pull access denied for agnaistic, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

I dont care about docker and dont want to use, so I hope there's a way to run it in anonymous state without it.

**Comment by sandwichdoge** [comment]
@sceuick A button to Import/Export convos sounds good, as you have control of the output data format, so the design is extendable. Plus not everyone will know where to backup/restore the saved convo files, it actually took me a while to find where the convos are stored in Tavern.
I think using mongo for persistence is fine, it'll save you the headaches of dealing with filesystems in the future.

@kakhulu31 You can try this command. I cloned the project on Windows and ran this and it basically just worked:
```
cd agn-ai
docker compose -p agnai -f self-host.docker-compose.yml up -d
```
There's also the instructions to run without docker in the README I think.

**Comment by gtaltatra** [comment]
>You can try this command

I specifically mentioned this command and my issues with it. 

>There's also the instructions to run without docker in the README I think

Can you please actually read my post before answering it? I want to run it in anonymous state while having mongodb files, readme doesnt include this part

**Comment by sandwichdoge** [comment]
@kakhulu31 It seems Docker for Windows doesn't understand the shortened link. This one should work if you're willing to use Docker.
```
docker run -dt --restart=always -p 3001:3001  ghcr.io/luminai-companion/agnaistic:latest 
```

**Comment by gtaltatra** [comment]
>Exporting and importing your anonymous state. This probably wouldn't been too hard at all and could be implemented very quickly.

Actually no, I just found out that its limited to 5mb. 

>Using alternate persistence strategies such as JSON files or SQLite. This would be a lot more work as I would have to duplicate my persistence code.

So this option should be much better.

**Comment by sceuick** [comment]
Hopefully this is resolved by using JSON storage. Re-open if it's not.
