### ISSUE TITLE
Character generation with novelai fails on selfhosted with silent error

### ISSUE THREAD

**Issue by novakda** [agnaistic/agnai#844]
**Describe the bug**
Character generation in the character creation screen fails silently, with an error in the console:

```
messages.ts:127 Uncaught (in promise) Error: opts.gen.order.map is not a function
    at Object.guidance (messages.ts:127:63)
    at async generateChar (generate-char.ts:32:40)
    at async Object.generateCharacter (editor.ts:242:5)
    at async generateCharacter (CreateCharacterForm.tsx:151:5)
```

The root cause appears to be common/util.ts!deepClone, which is not copying arrays properly.

for example, the order in the preset is coming out as 

 [6, 2, 3, 0, 4, 1, 5]

But it's getting something like {0:6, 1:2, 2:3, 3:0, 4:1, 5:5} from deepClone along the way,

**To Reproduce**

Having setup the application on Windows:

npm run deps
npm run start:win

Ensure a novelai key has been set and the api is available.

1. Open the new character screen.
2. Leave Description blank, and select "NovelAI - Kayra" from presets.
3. Select the Generate button. 
4. Observe the Generate button briefly switches to "Generating..." and back again,but nothing else happens.

In the browser dev tools, an error appears:

```
messages.ts:127 Uncaught (in promise) Error: opts.gen.order.map is not a function
    at Object.guidance (messages.ts:127:63)
    at async generateChar (generate-char.ts:32:40)
    at async Object.generateCharacter (editor.ts:242:5)
    at async generateCharacter (CreateCharacterForm.tsx:151:5)
```

**Expected behavior**
Character data is updated from NovelAI and no errors appear.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chromec 
 - Version: 122

**Additional context**

It appears to be barfing when trying to parse opts.gen.order.map becasue it's getting an object instead of an array.

Replacing deepClone with structuredClone() available in modern JavaScript engines (e.g. Node 17+) appears to correct the problem, and the character information generates.

I have not submitted a pull request because I am not yet familiar enough with the codebase or this project's development process. I'd be happy to answer any questions though,

Character generation works fine with Agniastic on agnai.chat, but not with novelai.

**Comment by sceuick** [comment]
This should be resolved now.
