### ISSUE TITLE
Request: implementation of Claude 3 models

### ISSUE THREAD

**Issue by paracule** [agnaistic/agnai#854]
Humbly requesting the implementation of Claude 3 models claude-3-opus-20240229 and claude-3-sonnet-20240229

Perhaps notably these models use the [Messages API](https://docs.anthropic.com/claude/reference/messages_post) exclusively rather than the previous text completion API , I am not sure whether the pre-filling mechanism would also need to be adjusted for the method they demonstrate on the page

**Comment by Arket7** [comment]
Useless request

pon., 4 mar 2024, 20:00 użytkownik paracule ***@***.***>
napisał:

**Comment by paracule** [comment]
@Arket7 I’d quite like it

**Comment by sceuick** [comment]
I'll accept for PR for this as it'll be a decent refactor and I don't have access to Claude models to test any changes with.

**Comment by sceuick** [comment]
I've added this now. I haven't tested the quality of the responses and most Claude features, but the legwork is done if anyone else needs to touch things up.
