### ISSUE TITLE
Top right menu not usable on iOS

### ISSUE THREAD

**Issue by breastlife** [agnaistic/agnai#856]
**Describe the bug**
The top right menu (the one with enable editing, UI, settings, etc), cannot be used on iOS (iPad). Once you click on it to open it, it shows up, but if you try to press any option, it goes away. While most of the options are accessible elsewhere, this makes it impossible to enable editing.

**Comment by breastlife** [comment]
Using the website.

**Comment by sceuick** [comment]
Finally reproduced and hopefully resolved this issue.
