### ISSUE TITLE
"Unexpected end of JSON input" when generating a reply.

### ISSUE THREAD

**Issue by mortilla** [agnaistic/agnai#857]
**Describe the bug**
When generating a reply it start streaming, but right after message ends an exception (below) occurs, and the message doesn't register properly (regenerate button doesn't move to it, delete button doesn't work). The message disappears after page refresh (F5). 

```
[api] [2024-03-09T04:45:53Z] INFO (app/10269): start request
[api]     requestId: "769cf9ad-5852-4fbd-bac4-05064d4a2e01"
[api]     url: "/api/chat/6e9a5af9-8e1c-409a-bf6a-06f086a80c45/generate"
[api]     method: "POST"
[api]     user: "mortilla"
[api] [2024-03-09T04:45:53Z] INFO (app/10269): end request
[api]     requestId: "769cf9ad-5852-4fbd-bac4-05064d4a2e01"
[api]     url: "/api/chat/6e9a5af9-8e1c-409a-bf6a-06f086a80c45/generate"
[api]     method: "POST"
[api]     user: "mortilla"
[api]     duration: 6
[api]     statusCode: 200
[api] [2024-03-09T04:45:57Z] ERROR (app/10269): Unhandled exception
[api]     err: "Unexpected end of JSON input"
```

**To Reproduce**
1. Start new chat.
2. Send a message.
3. See the exception.

**Expected behavior**
A chat could be continued.

**Screenshots**
N/A

**Desktop (please complete the following information):**
```
[mortilla@zbox ~]$ firefox --version
Mozilla Firefox 123.0.1
[mortilla@zbox ~]$ chromium --version
Chromium 122.0.6261.111 Arch Linux
[mortilla@zbox ~]$ uname -a
Linux zbox 6.7.9-artix1-1 #1 SMP PREEMPT_DYNAMIC Fri, 08 Mar 2024 14:08:26 +0000 x86_64 GNU/Linux
[mortilla@zbox ~]$ node --version
v21.7.0
[mortilla@zbox ~]$ npm --version
10.5.0
```

**Additional context**
I'm using "3rd party" service with Llama.cpp running at separate machine.

The exception could be traced to `srv/adapter/ooba.ts:199`. After all the chunks has been steamed, there is one last message that contains a full prompt, and for some reason it comes in truncated, causing JSON.Parse() to fail.

However, if I'm stepping trough each chunk with the debugger, that last message comes in fully and the exception never occurs (and the chat behaves as expected).

**Comment by sceuick** [comment]
I recently encountered this and did make some tweaks.
May be all fixed now. Re-open if it's still an issue and I'll dig into it.
