### ISSUE TITLE
Chat history being lost and cut

### ISSUE THREAD

**Issue by BoredOwner** [agnaistic/agnai#858]
I see chat history saved on "agnai.chat" website being cut, i.e. fails to load at certain point as it being actually lost. Also I see that only limited chat history can be imported successfully, up to 120 messages as I was able to reproduce. This leads me to suggestion that it is some limitations of max chat history import and limitations about how long and how lengthily chat history "agnai.chat" store before the older messages of chat history being deleted. However I also see that at least one of chat history being previously imported by me to "agnai.chat" still saved and loading successfully from the end to beginning while being both old and quite long (700+ messages). Which is makes my supposition illegit.

So now I have "agnai.chat" not preserving my latter chat histories and failing to import whole chat history, as much I can see.

Is it sort of technical issue or actually not a bug but non-subscribed account limitation? Thank you!

UPD: New detail spotted. After recent agnai.chat update I was able to retrieve some conversations history previously appearing to be "cut and lost". I was also able to import 1 lengthily  conversation fully and this particular one re-imported conversation still appears accessible and uncut. However other conversation that was fully accessible some time after recent update now seems "cut" to the latest 160 messages. So now I have the same issue as described before. And I leaning to cautiously presume some kind of server side issue with nature unknown to me.

**Comment by sceuick** [comment]
The entire chat history is now retrieved when opening a chat rather than paging through it.

**Comment by BoredOwner** [comment]
No changes seen at the moment. Even history importing "breaks" at exactly same point as before.

**Comment by BoredOwner** [comment]
> The entire chat history is now retrieved when opening a chat rather than paging through it.

No changes seen at the moment. Even history importing "breaks" at exactly same point as before.
