### ISSUE TITLE
Dynamic temperature on Agnai models - take 2

### ISSUE THREAD

**Issue by 2cute4name** [agnaistic/agnai#867]
My previous feature request was closed because dynamic temperature was implemented for Kobold and Aphrodite third party models. However, this is not what I meant. What I asked for was dynamic temperature on Agnai's own models as an option, since I have heard of many people using it these days, it sounds like something I could personally use, and have seen quite a few other people express interest in that setting as well. Please consider adding it as a sampler to Agnai models.

**Comment by sceuick** [comment]
This is mostly all done now. Just needs to be rolled out.
