### ISSUE TITLE
Quadratic sampling for Agnai models

### ISSUE THREAD

**Issue by 2cute4name** [agnaistic/agnai#868]
From what I have heard, quadratic sampling is a new, widely used sampler, designed to get creative responses with any temperature. I only have a vague idea of how it works, but I would love to see it on Agnai for the built-in models, since it sounds like it could be useful (along with dynamic temperature, which I created a separate request for). Hopefully it'll be implemented at some point. Thank you!

**Comment by sceuick** [comment]
I believe this has also been added, just needs to be rolled out to some models.
