### ISSUE TITLE
poe.com support

### ISSUE THREAD

**Issue by ytpk** [agnaistic/agnai#87]
Hello! I recently found a free platform for testing models ranging from Bloomz and Alpaca to GPT-4 and GPT-3.5 Turbo. Here's the link, comrades and anons! https://github.com/ading2210/openplayground-api I hope to see this integration in this project (the only catch is that authentication goes through two-factor code and email along with a cookie token). The maximum context length is 5000 characters.

**Comment by ytpk** [comment]
and 'poe' api - only gpt 3.5 turbo https://github.com/ading2210/poe-api

**Comment by ytpk** [comment]
k. nat.dev eerily do not like using the service through the api, so the option remains with the poe

**Comment by sceuick** [comment]
I'm unlikely to support this at the moment as I believe the authors of that project has stated they don't want "bot usage".
