### ISSUE TITLE
(Feature Request) Prefill Option for OpenRouter for Claude

### ISSUE THREAD

**Issue by stars-blue2081** [agnaistic/agnai#889]
**Is your feature request related to a problem? Please describe.**
While not a significant issue, it would be nice to have the prefill option for Claude via OpenRouter like for Claude via official API. This would minimize the necessity for long-winded jailbreaks, particularly the drawback that arises when Claude must express its understanding of user instructions rather than just generating a clean response without comments.

**Comment by sceuick** [comment]
This is done along with a lot of extra sampling parameters.
