### ISSUE TITLE
Can't update memory books in a chat

### ISSUE THREAD

**Issue by severedisrepair** [agnaistic/agnai#894]
**Describe the bug**
While in a chat with a bot, I can't change the memory book. When I try, I get an error message: "Failed to update book: Request body is invalid: .name is undefined". For some reason, the name slot is erased when I try to save. Adding the name back just causes another error message: "Failed to update book: Request body is invalid: .entries is undefined".
Changing and saving memory books through the library seems to work fine.
This issue started today.

I'm using a Desktop.
OS: Windows 10
Browser: Brave Browser [Version 1.64.116 Chromium: 123.0.6312.105 (Official Build) (64-bit)]

**Comment by sceuick** [comment]
Fixing this at the moment.

**Comment by sceuick** [comment]
Fix deploying for this now. Re-open if it's not resolved in 5-10minutes after refreshing.

**Comment by severedisrepair** [comment]
The issue with editing seems to be fixed, but I noticed that I can't seem to delete entries in the memory books. Nothing happens when I click on the cross, either in a chat or in the library.

**Comment by severedisrepair** [comment]
> Fix deploying for this now. Re-open if it's not resolved in 5-10minutes after refreshing.

The issue with editing seems to be fixed, but I noticed that I can't seem to delete entries in the memory books. Nothing happens when I click on the cross, either in a chat or in the library.

**Comment by sceuick** [comment]
Disable the entries for now. I'll fix this first thing.
