### ISSUE TITLE
Mancer models list missing cr/token cost information

### ISSUE THREAD

**Issue by Spacellary** [agnaistic/agnai#916]
**Describe the bug**
Mancer models list missing cr/token cost information...
I believe caused by website changes.

**To Reproduce**
1. Go to 'Presets'
2. Click on ''Mancer'
3. Click the model selection dropdown menu

**Expected behavior**
Expected to see the credits/token cost of each model in the list

**Screenshots**
![Screenshot_2024-04-24-19-01-32-209_com kiwibrowser browser](https://github.com/agnaistic/agnai/assets/39604793/2eb664ad-6faf-4d06-93e7-2acd2d964975)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 11
 - OS: Android 13/MIUI 12
 - Kiwi Browser/Chromium - Latest

**Comment by sceuick** [comment]
Ah, they probably changed their API. Fixed in upcoming release.
