### ISSUE TITLE
[Feature] OpenAI model request.

### ISSUE THREAD

**Issue by Mike-Turtle** [agnaistic/agnai#922]
**Is your feature request related to a problem? Please describe.**
Currently there is no option to choose the latest snapshot of OpenAI GPT4 Turbo model. The only direct choices are 1106 and 0125 snapshots.

**Describe the solution you'd like**
Please, add an option to directly choose 0409 snapshot of GPT4 Turbo to the available list in the OpenAI model family in 3rd party AI Service Preset.

Thank you!
![GPT](https://github.com/agnaistic/agnai/assets/146708739/35429fb8-bb32-444c-8388-0d40eb469f66)

**Comment by sceuick** [comment]
Closing as resolved
