### ISSUE TITLE
OAI Turbo adapter ignores preset maxContextLength/falls back to 2048

### ISSUE THREAD

**Issue by khanonnie** [agnaistic/agnai#93]
I noticed some strange behavior when working on a bot with larger definitions, where the prompt I was seeing in the terminal window was much shorter than expected given Turbo's 4096 context limit. I confirmed that my generation presets were set correctly, and confirmed they were being sent to the server correctly via the network tab, and eventually realized that the call to `mapPresetsToAdapter` in _srv/adapter/generate.ts#createTextStreamV2_ was stripping `maxContextLength` from the settings object provided to the controller.

This seems to be fixable by adding the key to the `serviceGenMap` in _common/presets.ts_. 

```ts
  openai: {
    // ...
    maxContextLength: 'maxContextLength',
```

Easy enough for me to fix that one, ~~but I'm thinking this might be happening to other adapters as well~~ and I don't fully understand how the presets are being used/transformed for every other adapter.  From my understanding `serviceGenMap` is mapping Agnai keys to the ones expected by each particular service, so blindly adding `maxContextLength` to each of them might not be appropriate if that value starts getting passed to the service's API.

edit: This appears to be specific to turbo, see https://github.com/luminai-companion/agn-ai/pull/94#issuecomment-1484368403

It seems like `maxContextLength` maybe should be special-cased, since you probably never actually want to pass it to the downstream service as you're just using it to build the prompt within Agnai.

**Comment by khanonnie** [comment]
PR opened for OAI but won't fix the issue for other adapters if it exists. (#94)

**Comment by sceuick** [comment]
The service gen map is specifically for what data gets sent to the backing service.
It's probably overkill. The context limit is used in the `createPrompt` / `createPromptWithParts`.

**Comment by khanonnie** [comment]
Looks fixed to me on dev, thanks!
