### ISSUE TITLE
Expand {{roll}} placeholder to include dice notation.

### ISSUE THREAD

**Issue by rankcody** [agnaistic/agnai#970]
**Is your feature request related to a problem? Please describe.**
The current implementation of the {{roll}} placeholder is very limited. You can't roll in a range that doesn't start at one (ex. if you wanted to pick a number from 0 to 9, you can't with the current implementation). You can't use multiple dice and/or have it pick the highest/lowest x number of dice, which is useful for adjusting the probability of rolls.

**Describe the solution you'd like**
Add dice notation capabilities to rolls.
https://en.wikipedia.org/wiki/Dice_notation
xdy indicates that x number of y sided dice is being rolled
Hx/Lx appended to the end of a group of dice indicates to keep x number of the highest/lowest dice results in the group
you can combine dice groups with each other or integers using basic math operators.

ex. {{roll 2d4H1+3d6L2-9}}
2 is the number of dice being thrown
d4 is the sides on each dice being thrown
H1 indicates that only the highest dice rolled is being kept for the result
3d6L2 is another set of dice (three six sided die take the two lowest) being thrown and added to the total
-9 subtracts 9 from the total

Going back to the example of rolling a number from 0 to 9, it'd be {{roll 1d10-1}}. Out of all the things to add, I think being able to add/subtract a number is the most important.

**Describe alternatives you've considered**
Having the AI try and do that math in the background (ex. Calculate {{roll 10}}-1). This is obviously not ideal for actually achieving RNG, especially since the AI flubs math sometimes.

**Additional context**

**Comment by sceuick** [comment]
This'll be in the next release.
