### ISSUE TITLE
Private Vulnerability Reporting

### ISSUE THREAD

**Issue by ropwareJB** [agnaistic/agnai#980]
Please enable private vulnerability reporting for this repository:
https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

Secondly, I have opened a PR to add a `SECURITY.md` disclosure policy: https://github.com/agnaistic/agnai/pull/979

**Comment by sceuick** [comment]
Done. Thank you.
