### ISSUE TITLE
Description lost when creating a character

### ISSUE THREAD

**Issue by acidbubbles** [agnaistic/agnai#99]
Commit: 85df245

To reproduce:

- In /character/create, create a character including the Description field and press Create
- The description is not shown on the characters page
- Editing the character indeed shows the field as empty
- When filling the field and pressing Update, now it gets updated correctly

This is unrelated but in the same page; the empty attributes are lost when saving without a value. I think it's fine but I expected them to still be there. I'll let you be the judge of whether the attribute name is worth keeping or not :)

**Comment by sceuick** [comment]
Thanks, just pushed a fix.

**Comment by sceuick** [comment]
Regarding the 'empty attributes', it definitely was deliberate to remove them if they're empty.
I can definitely see an argument for retaining them, but simply not using them when building the prompt.

**Comment by acidbubbles** [comment]
I'll try and push fixes myself down the road, I'll try and get comfortable with the code before making suggestions though! (If they're welcome). Thanks!

**Comment by acidbubbles** [comment]
As far as I can tell it still doesn't work :) At least it didn't on commit aed57c072d2b7e3dd9cb702fccc9f2431a363d3b
